import { WorksheetConfig, WorksheetData, ShapeName, SHAPE_COLORS, getShapeSVG, getShapeRawSVG } from '@/lib/shapes';
import { LETTER_PATHS, StrokePoint } from '@/lib/letterPaths';

interface Props {
  config: WorksheetConfig;
  data: WorksheetData;
}

const W = 595;
const H = 842;
const MARGIN = 40;
const BW_FILL = 'none';
const BW_STROKE = '#1E293B';

// Border style helpers
function getBorderAttrs(config: WorksheetConfig, strokeColor = '#CBD5E1', width = 1.5): string {
  const dash = config.borderStyle === 'dotted' ? ` stroke-dasharray="4 4"` : '';
  const rx = config.borderStyle === 'rounded' ? ` rx="8" ry="8"` : ` rx="3"`;
  return `fill="none" stroke="${strokeColor}" stroke-width="${width}"${dash}${rx}`;
}

function getCellBorderAttrs(config: WorksheetConfig, strokeColor = '#CBD5E1', width = 1): string {
  const dash = config.borderStyle === 'dotted' ? ` stroke-dasharray="4 4"` : '';
  const rx = config.borderStyle === 'rounded' ? ` rx="6" ry="6"` : ` rx="3"`;
  return `fill="none" stroke="${strokeColor}" stroke-width="${width}"${dash}${rx}`;
}

export default function WorksheetPreview({ config, data }: Props) {
  const getFill = (shape: ShapeName) => config.useColor ? SHAPE_COLORS[shape] : BW_FILL;
  const getStroke = (shape: ShapeName) => config.useColor ? SHAPE_COLORS[shape] : BW_STROKE;
  const getStrokeW = () => config.useColor ? 1.5 : 2.5;

  const shapeScale = config.difficulty === 'easy' ? 1.15 : config.difficulty === 'medium' ? 1.0 : 0.85;

  // Header font sizes
  const nameFontSize = config.headerFontSize === 'small' ? 14 : config.headerFontSize === 'large' ? 24 : 18;
  const nameWeight = config.headerBold ? '800' : '600';
  const ageStr = config.childAge !== null ? ` (Age ${config.childAge})` : '';
  const nameStr = config.childName ? config.childName + ageStr : '___________________';

  const headerSVG = `
    <text x="${W / 2}" y="${MARGIN + 22}" text-anchor="middle" font-family="Nunito, sans-serif" font-size="20" font-weight="800" fill="#0D9488">OTsheet.ai</text>
    <line x1="${MARGIN}" y1="${MARGIN + 32}" x2="${W - MARGIN}" y2="${MARGIN + 32}" stroke="#E2E8F0" stroke-width="1" />
    <text x="${MARGIN}" y="${MARGIN + 52}" font-family="Nunito, sans-serif" font-size="${nameFontSize}" font-weight="${nameWeight}" fill="#334155">Name: ${nameStr}</text>
    <text x="${W - MARGIN}" y="${MARGIN + 52}" text-anchor="end" font-family="Inter, sans-serif" font-size="11" fill="#94A3B8">Date: ____/____/________</text>
    <text x="${W / 2}" y="${MARGIN + 72}" text-anchor="middle" font-family="Nunito, sans-serif" font-size="14" font-weight="700" fill="#1E293B">${data.instructions}</text>
  `;

  const footerSVG = `
    <line x1="${MARGIN}" y1="${H - MARGIN - 20}" x2="${W - MARGIN}" y2="${H - MARGIN - 20}" stroke="#E2E8F0" stroke-width="1" />
    <text x="${MARGIN}" y="${H - MARGIN - 4}" font-family="Inter, sans-serif" font-size="10" font-weight="600" fill="#94A3B8">Skill: ${data.skillLabel}</text>
    <text x="${W - MARGIN}" y="${H - MARGIN - 4}" text-anchor="end" font-family="Inter, sans-serif" font-size="9" fill="#CBD5E1">Generated by OTsheet.ai</text>
  `;

  let bodySVG = '';

  if (data.mode === 'find') {
    bodySVG = renderFindMode(config, data, shapeScale, getFill, getStroke, getStrokeW);
  } else if (data.mode === 'missing') {
    bodySVG = renderMissingMode(config, data, shapeScale, getFill, getStroke, getStrokeW);
  } else if (data.mode === 'pattern') {
    bodySVG = renderPatternMode(config, data, shapeScale, getFill, getStroke, getStrokeW);
  } else if (data.mode === 'count') {
    bodySVG = renderCountMode(config, data, shapeScale, getFill, getStroke, getStrokeW);
  } else if (data.mode === 'copy') {
    bodySVG = renderCopyMode(config, data, shapeScale, getFill, getStroke, getStrokeW);
  } else if (data.mode === 'sequence') {
    bodySVG = renderSequenceMode(config, data, shapeScale, getFill, getStroke, getStrokeW);
  } else if (data.mode === 'oddOneOut') {
    bodySVG = renderOddOneOutMode(config, data, shapeScale, getFill, getStroke, getStrokeW);
  } else if (data.mode === 'mirror') {
    bodySVG = renderMirrorMode(config, data, shapeScale, getFill, getStroke, getStrokeW);
  } else if (data.mode === 'figureGround') {
    bodySVG = renderFigureGroundMode(config, data, shapeScale, getFill, getStroke, getStrokeW);
  } else if (data.mode === 'closure') {
    bodySVG = renderClosureMode(config, data, shapeScale, getFill, getStroke, getStrokeW);
  } else if (data.mode === 'traceName') {
    bodySVG = renderTraceNameMode(config, data);
  } else if (data.mode === 'handwriting') {
    bodySVG = renderHandwritingMode(config, data);
  }

  const svgContent = `
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H}" width="100%" height="100%">
      <rect width="${W}" height="${H}" fill="white" rx="4" />
      ${headerSVG}
      ${bodySVG}
      ${footerSVG}
    </svg>
  `;

  return (
    <div
      id="worksheet-preview"
      className="bg-card rounded-xl shadow-lg border border-border overflow-hidden"
      style={{ aspectRatio: '210/297', maxHeight: '85vh' }}
      dangerouslySetInnerHTML={{ __html: svgContent }}
    />
  );
}

// ========== MODE 1: FIND THE SHAPE ==========
function renderFindMode(
  config: WorksheetConfig,
  data: WorksheetData,
  shapeScale: number,
  getFill: (s: ShapeName) => string,
  getStroke: (s: ShapeName) => string,
  getStrokeW: () => number,
) {
  const targetShape = data.targetShape!;
  const grid = data.grid!;
  const size = config.gridSize;

  const refBoxY = MARGIN + 85;
  const refBoxH = 64;
  const refBoxW = 200;
  const refBoxX = (W - refBoxW) / 2;

  let svg = '';
  svg += `<rect x="${refBoxX}" y="${refBoxY}" width="${refBoxW}" height="${refBoxH}" rx="8" fill="none" stroke="#94A3B8" stroke-width="2" stroke-dasharray="8,5" />`;
  svg += `<text x="${refBoxX + 12}" y="${refBoxY + 16}" font-family="Inter, sans-serif" font-size="10" fill="#64748B">Find this shape:</text>`;
  svg += getShapeSVG(targetShape, refBoxX + refBoxW / 2, refBoxY + refBoxH / 2 + 5, 50 * shapeScale, getFill(targetShape), getStroke(targetShape), getStrokeW());

  const gridTop = refBoxY + refBoxH + 20;
  const gridAreaH = H - gridTop - MARGIN - 35;
  const gridAreaW = W - MARGIN * 2;
  const cellSize = Math.min(gridAreaW / size, gridAreaH / size);
  const gridW = cellSize * size;
  const gridH = cellSize * size;
  const gridX = (W - gridW) / 2;

  svg += `<rect x="${gridX}" y="${gridTop}" width="${gridW}" height="${gridH}" ${getBorderAttrs(config, '#CBD5E1', 2)} />`;

  if (config.showGridLines) {
    for (let i = 1; i < size; i++) {
      svg += `<line x1="${gridX + i * cellSize}" y1="${gridTop}" x2="${gridX + i * cellSize}" y2="${gridTop + gridH}" stroke="#E2E8F0" stroke-width="1" />`;
      svg += `<line x1="${gridX}" y1="${gridTop + i * cellSize}" x2="${gridX + gridW}" y2="${gridTop + i * cellSize}" stroke="#E2E8F0" stroke-width="1" />`;
    }
  }

  grid.forEach((row, r) => {
    row.forEach((cell, c) => {
      const cx = gridX + c * cellSize + cellSize / 2;
      const cy = gridTop + r * cellSize + cellSize / 2;
      svg += getShapeSVG(cell.shape, cx, cy, cellSize * shapeScale, getFill(cell.shape), getStroke(cell.shape), getStrokeW(), cell.rotation);
    });
  });

  if (config.showAnswerKey) {
    let count = 0;
    grid.forEach(row => row.forEach(cell => { if (cell.isTarget) count++; }));
    svg += `<text x="${W / 2}" y="${gridTop + gridH + 18}" text-anchor="middle" font-family="Inter, sans-serif" font-size="10" fill="#94A3B8">Answer: ${count} ${targetShape}${count !== 1 ? 's' : ''}</text>`;
  }

  return svg;
}

// ========== MODE 2: MISSING SHAPE ==========
function renderMissingMode(
  config: WorksheetConfig,
  data: WorksheetData,
  shapeScale: number,
  getFill: (s: ShapeName) => string,
  getStroke: (s: ShapeName) => string,
  getStrokeW: () => number,
) {
  const refShapes = data.referenceShapes!;
  const puzzles = data.missingPuzzles!;

  let svg = '';

  const refY = MARGIN + 85;
  const refH = 56;
  const refW = Math.min(refShapes.length * 80, W - MARGIN * 2);
  const refX = (W - refW) / 2;
  const refCellW = refW / refShapes.length;

  svg += `<rect x="${refX}" y="${refY}" width="${refW}" height="${refH}" rx="8" fill="#F8FAFC" stroke="#E2E8F0" stroke-width="1.5" />`;
  svg += `<text x="${W / 2}" y="${refY - 6}" text-anchor="middle" font-family="Inter, sans-serif" font-size="10" fill="#64748B">Reference Shapes:</text>`;

  refShapes.forEach((shape, i) => {
    const cx = refX + i * refCellW + refCellW / 2;
    const cy = refY + refH / 2;
    svg += getShapeSVG(shape, cx, cy, 42, getFill(shape), getStroke(shape), getStrokeW());
    svg += `<text x="${cx}" y="${cy + 28}" text-anchor="middle" font-family="Inter, sans-serif" font-size="8" fill="#94A3B8">${shape}</text>`;
  });

  const puzzleTop = refY + refH + 24;
  const availH = H - puzzleTop - MARGIN - 35;
  const cols = puzzles.length <= 3 ? puzzles.length : Math.min(3, puzzles.length);
  const rows = Math.ceil(puzzles.length / cols);
  const puzzleAreaW = W - MARGIN * 2;
  const puzzleCellW = puzzleAreaW / cols;
  const puzzleCellH = availH / rows;
  const subGridMaxSize = Math.min(puzzleCellW - 30, puzzleCellH - 30, 130);

  puzzles.forEach((puzzle, idx) => {
    const col = idx % cols;
    const row = Math.floor(idx / cols);
    const pSize = puzzle.grid.length;
    const cellSz = subGridMaxSize / pSize;
    const px = MARGIN + col * puzzleCellW + (puzzleCellW - subGridMaxSize) / 2;
    const py = puzzleTop + row * puzzleCellH + (puzzleCellH - subGridMaxSize) / 2;

    svg += `<text x="${px + subGridMaxSize / 2}" y="${py - 6}" text-anchor="middle" font-family="Nunito, sans-serif" font-size="11" font-weight="700" fill="#64748B">${idx + 1}.</text>`;
    svg += `<rect x="${px}" y="${py}" width="${subGridMaxSize}" height="${subGridMaxSize}" ${getCellBorderAttrs(config, '#CBD5E1', 1.5)} />`;

    if (config.showGridLines) {
      for (let i = 1; i < pSize; i++) {
        svg += `<line x1="${px + i * cellSz}" y1="${py}" x2="${px + i * cellSz}" y2="${py + subGridMaxSize}" stroke="#E2E8F0" stroke-width="0.8" />`;
        svg += `<line x1="${px}" y1="${py + i * cellSz}" x2="${px + subGridMaxSize}" y2="${py + i * cellSz}" stroke="#E2E8F0" stroke-width="0.8" />`;
      }
    }

    puzzle.grid.forEach((gridRow, r) => {
      gridRow.forEach((cell, c) => {
        const cx = px + c * cellSz + cellSz / 2;
        const cy = py + r * cellSz + cellSz / 2;
        if (cell.isBlank) {
          svg += `<text x="${cx}" y="${cy + 5}" text-anchor="middle" font-family="Inter, sans-serif" font-size="${cellSz * 0.4}" fill="#CBD5E1">?</text>`;
          svg += `<rect x="${cx - cellSz * 0.38}" y="${cy - cellSz * 0.38}" width="${cellSz * 0.76}" height="${cellSz * 0.76}" rx="4" fill="none" stroke="#CBD5E1" stroke-width="1" stroke-dasharray="4,3" />`;
        } else {
          svg += getShapeSVG(cell.shape, cx, cy, cellSz * shapeScale, getFill(cell.shape), getStroke(cell.shape), getStrokeW(), cell.rotation);
        }
      });
    });
  });

  if (config.showAnswerKey) {
    const answers = puzzles.map((p, i) => `${i + 1}:${p.answer}`).join('  ');
    svg += `<text x="${W / 2}" y="${H - MARGIN - 28}" text-anchor="middle" font-family="Inter, sans-serif" font-size="9" fill="#94A3B8">Answers: ${answers}</text>`;
  }

  return svg;
}

// ========== MODE 3: MATCH PATTERN ==========
function renderPatternMode(
  config: WorksheetConfig,
  data: WorksheetData,
  shapeScale: number,
  getFill: (s: ShapeName) => string,
  getStroke: (s: ShapeName) => string,
  getStrokeW: () => number,
) {
  const puzzles = data.patternPuzzles!;
  let svg = '';

  const startY = MARGIN + 88;
  const availH = H - startY - MARGIN - 35;
  const rowH = availH / puzzles.length;
  const patternBoxSize = Math.min(rowH - 16, 90);
  const optionBoxSize = Math.min(patternBoxSize * 0.82, 68);

  const leftColX = MARGIN + 20;
  const rightColX = W / 2 + 10;
  const optionSpacing = (W - rightColX - MARGIN - 10) < optionBoxSize * 3.5
    ? optionBoxSize + 8
    : optionBoxSize + 16;

  puzzles.forEach((puzzle, pIdx) => {
    const rowY = startY + pIdx * rowH + (rowH - patternBoxSize) / 2;

    svg += `<text x="${leftColX - 12}" y="${rowY + patternBoxSize / 2 + 4}" text-anchor="middle" font-family="Nunito, sans-serif" font-size="13" font-weight="700" fill="#64748B">${pIdx + 1}.</text>`;
    svg += renderMiniGrid(puzzle.pattern, leftColX, rowY, patternBoxSize, shapeScale, getFill, getStroke, getStrokeW, config.showGridLines, config);

    const arrowX = leftColX + patternBoxSize + 14;
    const arrowY = rowY + patternBoxSize / 2;
    svg += `<line x1="${arrowX}" y1="${arrowY}" x2="${arrowX + 20}" y2="${arrowY}" stroke="#94A3B8" stroke-width="1.5" />`;
    svg += `<polygon points="${arrowX + 20},${arrowY - 4} ${arrowX + 28},${arrowY} ${arrowX + 20},${arrowY + 4}" fill="#94A3B8" />`;

    puzzle.options.forEach((option, oIdx) => {
      const ox = rightColX + oIdx * optionSpacing;
      const oy = rowY + (patternBoxSize - optionBoxSize) / 2;

      svg += `<text x="${ox + optionBoxSize / 2}" y="${oy - 4}" text-anchor="middle" font-family="Inter, sans-serif" font-size="9" font-weight="600" fill="#94A3B8">${String.fromCharCode(65 + oIdx)}</text>`;
      svg += renderMiniGrid(option, ox, oy, optionBoxSize, shapeScale * 0.85, getFill, getStroke, getStrokeW, false, config);
      svg += `<circle cx="${ox + optionBoxSize / 2}" cy="${oy + optionBoxSize + 8}" r="3" fill="none" stroke="#CBD5E1" stroke-width="1" />`;
    });

    svg += `<circle cx="${leftColX + patternBoxSize / 2}" cy="${rowY + patternBoxSize + 8}" r="3" fill="none" stroke="#CBD5E1" stroke-width="1" />`;
  });

  if (config.showAnswerKey) {
    const answers = puzzles.map((p, i) => `${i + 1}→${String.fromCharCode(65 + p.correctIndex)}`).join('  ');
    svg += `<text x="${W / 2}" y="${H - MARGIN - 28}" text-anchor="middle" font-family="Inter, sans-serif" font-size="9" fill="#94A3B8">Answers: ${answers}</text>`;
  }

  return svg;
}

function renderMiniGrid(
  grid: { shape: ShapeName; rotation?: number }[][],
  x: number,
  y: number,
  size: number,
  scale: number,
  getFill: (s: ShapeName) => string,
  getStroke: (s: ShapeName) => string,
  getStrokeW: () => number,
  showLines: boolean,
  config?: WorksheetConfig,
): string {
  const rows = grid.length;
  const cols = grid[0].length;
  const cellW = size / cols;
  const cellH = size / rows;
  let svg = '';

  if (config) {
    svg += `<rect x="${x}" y="${y}" width="${size}" height="${size}" ${getCellBorderAttrs(config, '#CBD5E1', 1.5)} />`;
  } else {
    svg += `<rect x="${x}" y="${y}" width="${size}" height="${size}" fill="none" stroke="#CBD5E1" stroke-width="1.5" rx="3" />`;
  }

  if (showLines) {
    for (let i = 1; i < cols; i++) {
      svg += `<line x1="${x + i * cellW}" y1="${y}" x2="${x + i * cellW}" y2="${y + size}" stroke="#E2E8F0" stroke-width="0.8" />`;
    }
    for (let i = 1; i < rows; i++) {
      svg += `<line x1="${x}" y1="${y + i * cellH}" x2="${x + size}" y2="${y + i * cellH}" stroke="#E2E8F0" stroke-width="0.8" />`;
    }
  }

  grid.forEach((row, r) => {
    row.forEach((cell, c) => {
      const cx = x + c * cellW + cellW / 2;
      const cy = y + r * cellH + cellH / 2;
      svg += getShapeSVG(cell.shape, cx, cy, Math.min(cellW, cellH) * scale, getFill(cell.shape), getStroke(cell.shape), getStrokeW(), cell.rotation);
    });
  });

  return svg;
}

// ========== MODE 4: FIND AND COUNT ==========
function renderCountMode(
  config: WorksheetConfig,
  data: WorksheetData,
  shapeScale: number,
  getFill: (s: ShapeName) => string,
  getStroke: (s: ShapeName) => string,
  getStrokeW: () => number,
) {
  const puzzle = data.countPuzzle!;
  const { grid, targetShapes } = puzzle;
  const ROWS = grid.length;
  const COLS = grid[0].length;

  let svg = '';

  const refY = MARGIN + 85;
  const refH = 62;
  const boxCount = targetShapes.length;
  const totalRefW = Math.min(boxCount * 100, W - MARGIN * 2);
  const refX = (W - totalRefW) / 2;
  const boxW = totalRefW / boxCount;

  targetShapes.forEach((shape, i) => {
    const bx = refX + i * boxW + 4;
    const bw = boxW - 8;
    svg += `<rect x="${bx}" y="${refY}" width="${bw}" height="${refH}" rx="6" fill="#F8FAFC" stroke="#CBD5E1" stroke-width="1.5" />`;
    svg += getShapeSVG(shape, bx + bw / 2, refY + 26, 36 * shapeScale, getFill(shape), getStroke(shape), getStrokeW());
    svg += `<line x1="${bx + bw * 0.25}" y1="${refY + refH - 10}" x2="${bx + bw * 0.75}" y2="${refY + refH - 10}" stroke="#94A3B8" stroke-width="1.5" />`;
  });

  const gridTop = refY + refH + 18;
  const gridAreaH = H - gridTop - MARGIN - 35;
  const gridAreaW = W - MARGIN * 2;
  const cellW = gridAreaW / COLS;
  const cellH = gridAreaH / ROWS;
  const cellSize = Math.min(cellW, cellH);
  const gridW = cellSize * COLS;
  const gridH = cellSize * ROWS;
  const gridX = (W - gridW) / 2;

  svg += `<rect x="${gridX}" y="${gridTop}" width="${gridW}" height="${gridH}" ${getBorderAttrs(config, '#CBD5E1', 2)} />`;

  if (config.showGridLines) {
    for (let c = 1; c < COLS; c++) {
      svg += `<line x1="${gridX + c * cellSize}" y1="${gridTop}" x2="${gridX + c * cellSize}" y2="${gridTop + gridH}" stroke="#E2E8F0" stroke-width="0.8" />`;
    }
    for (let r = 1; r < ROWS; r++) {
      svg += `<line x1="${gridX}" y1="${gridTop + r * cellSize}" x2="${gridX + gridW}" y2="${gridTop + r * cellSize}" stroke="#E2E8F0" stroke-width="0.8" />`;
    }
  }

  grid.forEach((row, r) => {
    row.forEach((cell, c) => {
      const cx = gridX + c * cellSize + cellSize / 2;
      const cy = gridTop + r * cellSize + cellSize / 2;
      svg += getShapeSVG(cell.shape, cx, cy, cellSize * shapeScale, getFill(cell.shape), getStroke(cell.shape), getStrokeW(), cell.rotation);
    });
  });

  if (config.showAnswerKey) {
    const answers = targetShapes.map(s => `${s}: ${puzzle.counts[s]}`).join('   ');
    svg += `<text x="${W / 2}" y="${gridTop + gridH + 16}" text-anchor="middle" font-family="Inter, sans-serif" font-size="9" fill="#94A3B8">Answers: ${answers}</text>`;
  }

  return svg;
}

// ========== MODE 5: COPY THE PATTERN ==========
function renderCopyMode(
  config: WorksheetConfig,
  data: WorksheetData,
  shapeScale: number,
  getFill: (s: ShapeName) => string,
  getStroke: (s: ShapeName) => string,
  getStrokeW: () => number,
) {
  const puzzles = data.copyPuzzles!;
  let svg = '';

  const startY = MARGIN + 88;
  const availH = H - startY - MARGIN - 35;
  const rowH = availH / puzzles.length;

  puzzles.forEach((puzzle, pIdx) => {
    const gridSize = puzzle.sourceGrid.length;
    const maxGridSz = Math.min(rowH - 20, 160);
    const cellSz = maxGridSz / gridSize;
    const gridSz = cellSz * gridSize;

    const rowY = startY + pIdx * rowH + (rowH - gridSz) / 2;
    const pairW = W - MARGIN * 2;
    const leftX = MARGIN + pairW * 0.05;
    const rightX = MARGIN + pairW * 0.55;

    svg += `<text x="${MARGIN}" y="${rowY + gridSz / 2 + 4}" font-family="Nunito, sans-serif" font-size="13" font-weight="700" fill="#64748B">${pIdx + 1}.</text>`;

    svg += `<rect x="${leftX}" y="${rowY}" width="${gridSz}" height="${gridSz}" ${getCellBorderAttrs(config, '#CBD5E1', 1.5)} />`;
    if (config.showGridLines) {
      for (let i = 1; i < gridSize; i++) {
        svg += `<line x1="${leftX + i * cellSz}" y1="${rowY}" x2="${leftX + i * cellSz}" y2="${rowY + gridSz}" stroke="#E2E8F0" stroke-width="0.8" />`;
        svg += `<line x1="${leftX}" y1="${rowY + i * cellSz}" x2="${leftX + gridSz}" y2="${rowY + i * cellSz}" stroke="#E2E8F0" stroke-width="0.8" />`;
      }
    }
    puzzle.sourceGrid.forEach((row, r) => {
      row.forEach((cell, c) => {
        const cx = leftX + c * cellSz + cellSz / 2;
        const cy = rowY + r * cellSz + cellSz / 2;
        svg += getShapeSVG(cell.shape, cx, cy, cellSz * shapeScale, getFill(cell.shape), getStroke(cell.shape), getStrokeW(), cell.rotation);
      });
    });

    const arrowX = leftX + gridSz + 8;
    const arrowY2 = rowY + gridSz / 2;
    svg += `<line x1="${arrowX}" y1="${arrowY2}" x2="${arrowX + 16}" y2="${arrowY2}" stroke="#94A3B8" stroke-width="1.5" />`;
    svg += `<polygon points="${arrowX + 16},${arrowY2 - 4} ${arrowX + 24},${arrowY2} ${arrowX + 16},${arrowY2 + 4}" fill="#94A3B8" />`;

    svg += `<rect x="${rightX}" y="${rowY}" width="${gridSz}" height="${gridSz}" ${getCellBorderAttrs(config, '#CBD5E1', 1.5)} />`;
    for (let i = 1; i < gridSize; i++) {
      svg += `<line x1="${rightX + i * cellSz}" y1="${rowY}" x2="${rightX + i * cellSz}" y2="${rowY + gridSz}" stroke="#E2E8F0" stroke-width="0.8" />`;
      svg += `<line x1="${rightX}" y1="${rowY + i * cellSz}" x2="${rightX + gridSz}" y2="${rowY + i * cellSz}" stroke="#E2E8F0" stroke-width="0.8" />`;
    }
  });

  return svg;
}

// ========== MODE 6: WHAT COMES NEXT ==========
function renderSequenceMode(
  config: WorksheetConfig,
  data: WorksheetData,
  shapeScale: number,
  getFill: (s: ShapeName) => string,
  getStroke: (s: ShapeName) => string,
  getStrokeW: () => number,
) {
  const puzzles = data.sequencePuzzles!;
  let svg = '';

  const startY = MARGIN + 88;
  const availH = H - startY - MARGIN - 35;
  const rowH = availH / puzzles.length;
  const cellSz = Math.min(rowH * 0.45, 50);

  puzzles.forEach((puzzle, pIdx) => {
    const rowY = startY + pIdx * rowH;
    const seqY = rowY + rowH * 0.18;

    svg += `<text x="${MARGIN + 4}" y="${seqY + cellSz / 2 + 4}" font-family="Nunito, sans-serif" font-size="12" font-weight="700" fill="#64748B">${pIdx + 1}.</text>`;

    const seqStartX = MARGIN + 28;
    for (let i = 0; i < 4; i++) {
      const cx = seqStartX + i * (cellSz + 8) + cellSz / 2;
      const cy = seqY + cellSz / 2;
      svg += `<rect x="${cx - cellSz / 2}" y="${cy - cellSz / 2}" width="${cellSz}" height="${cellSz}" ${getCellBorderAttrs(config, '#CBD5E1', 1)} />`;
      svg += getShapeSVG(puzzle.sequence[i].shape, cx, cy, cellSz * shapeScale, getFill(puzzle.sequence[i].shape), getStroke(puzzle.sequence[i].shape), getStrokeW(), puzzle.sequence[i].rotation);
    }

    const qx = seqStartX + 4 * (cellSz + 8) + cellSz / 2;
    const qy = seqY + cellSz / 2;
    svg += `<rect x="${qx - cellSz / 2}" y="${qy - cellSz / 2}" width="${cellSz}" height="${cellSz}" rx="4" fill="none" stroke="#CBD5E1" stroke-width="1.5" stroke-dasharray="6,4" />`;
    svg += `<text x="${qx}" y="${qy + 5}" text-anchor="middle" font-family="Nunito, sans-serif" font-size="${cellSz * 0.5}" font-weight="700" fill="#CBD5E1">?</text>`;

    const optStartX = seqStartX + 5 * (cellSz + 8) + 20;
    const optSize = cellSz * 0.85;
    puzzle.options.forEach((opt, oIdx) => {
      const ox = optStartX + oIdx * (optSize + 14) + optSize / 2;
      const oy = seqY + cellSz / 2;
      svg += `<text x="${ox}" y="${oy - optSize / 2 - 3}" text-anchor="middle" font-family="Inter, sans-serif" font-size="8" font-weight="600" fill="#94A3B8">${String.fromCharCode(65 + oIdx)}</text>`;
      svg += `<rect x="${ox - optSize / 2}" y="${oy - optSize / 2}" width="${optSize}" height="${optSize}" ${getCellBorderAttrs(config, '#94A3B8', 1)} />`;
      svg += getShapeSVG(opt.shape, ox, oy, optSize * shapeScale, getFill(opt.shape), getStroke(opt.shape), getStrokeW());
    });
  });

  if (config.showAnswerKey) {
    const answers = puzzles.map((p, i) => `${i + 1}→${String.fromCharCode(65 + p.correctIndex)}`).join('  ');
    svg += `<text x="${W / 2}" y="${H - MARGIN - 28}" text-anchor="middle" font-family="Inter, sans-serif" font-size="9" fill="#94A3B8">Answers: ${answers}</text>`;
  }

  return svg;
}

// ========== MODE 7: ODD ONE OUT ==========
function renderOddOneOutMode(
  config: WorksheetConfig,
  data: WorksheetData,
  shapeScale: number,
  getFill: (s: ShapeName) => string,
  getStroke: (s: ShapeName) => string,
  getStrokeW: () => number,
) {
  const rows = data.oddOneOutRows!;
  let svg = '';

  const startY = MARGIN + 88;
  const availH = H - startY - MARGIN - 35;
  const rowH = availH / rows.length;
  const cellSz = Math.min(rowH - 10, 60);
  const totalRowW = 5 * cellSz + 4 * 16;
  const rowStartX = (W - totalRowW) / 2;

  const isText = rows.length > 0 && rows[0].textItems && rows[0].textItems.length > 0;
  const fontSize = config.difficulty === 'easy' ? Math.min(cellSz * 0.7, 36) : config.difficulty === 'medium' ? Math.min(cellSz * 0.6, 28) : Math.min(cellSz * 0.5, 22);

  rows.forEach((row, rIdx) => {
    const rowY = startY + rIdx * rowH + (rowH - cellSz) / 2;

    svg += `<text x="${rowStartX - 18}" y="${rowY + cellSz / 2 + 4}" font-family="Nunito, sans-serif" font-size="12" font-weight="700" fill="#64748B">${rIdx + 1}.</text>`;

    if (isText && row.textItems) {
      row.textItems.forEach((char, i) => {
        const cx = rowStartX + i * (cellSz + 16) + cellSz / 2;
        const cy = rowY + cellSz / 2;
        svg += `<rect x="${cx - cellSz / 2}" y="${cy - cellSz / 2}" width="${cellSz}" height="${cellSz}" ${getCellBorderAttrs(config, '#CBD5E1', 1)} />`;
        svg += `<text x="${cx}" y="${cy + fontSize * 0.35}" text-anchor="middle" font-family="Inter, sans-serif" font-size="${fontSize}" font-weight="600" fill="#1E293B">${char}</text>`;
      });
    } else {
      row.items.forEach((cell, i) => {
        const cx = rowStartX + i * (cellSz + 16) + cellSz / 2;
        const cy = rowY + cellSz / 2;
        svg += `<rect x="${cx - cellSz / 2}" y="${cy - cellSz / 2}" width="${cellSz}" height="${cellSz}" ${getCellBorderAttrs(config, '#CBD5E1', 1)} />`;
        svg += getShapeSVG(cell.shape, cx, cy, cellSz * shapeScale, getFill(cell.shape), getStroke(cell.shape), getStrokeW(), cell.rotation);
      });
    }
  });

  if (config.showAnswerKey) {
    const answers = rows.map((r, i) => `${i + 1}:${r.oddIndex + 1}`).join('  ');
    svg += `<text x="${W / 2}" y="${H - MARGIN - 28}" text-anchor="middle" font-family="Inter, sans-serif" font-size="9" fill="#94A3B8">Answers (position): ${answers}</text>`;
  }

  return svg;
}

// ========== MODE 8: MIRROR IMAGE ==========
function renderMirrorMode(
  config: WorksheetConfig,
  data: WorksheetData,
  shapeScale: number,
  getFill: (s: ShapeName) => string,
  getStroke: (s: ShapeName) => string,
  getStrokeW: () => number,
) {
  const puzzles = data.mirrorPuzzles!;
  let svg = '';

  const startY = MARGIN + 88;
  const availH = H - startY - MARGIN - 35;
  const pairH = availH / puzzles.length;

  puzzles.forEach((puzzle, pIdx) => {
    const gridSize = puzzle.sourceGrid.length;
    const maxGridSz = Math.min(pairH - 30, 180, (W - MARGIN * 2 - 30) / 2);
    const cellSz = maxGridSz / gridSize;
    const gridSz = cellSz * gridSize;

    const pairY = startY + pIdx * pairH + (pairH - gridSz) / 2;
    const centerX = W / 2;
    const leftX = centerX - gridSz - 8;
    const rightX = centerX + 8;

    svg += `<text x="${W / 2}" y="${pairY - 8}" text-anchor="middle" font-family="Nunito, sans-serif" font-size="12" font-weight="700" fill="#64748B">${pIdx + 1}.</text>`;
    svg += `<line x1="${centerX}" y1="${pairY - 2}" x2="${centerX}" y2="${pairY + gridSz + 2}" stroke="#94A3B8" stroke-width="2" stroke-dasharray="8,5" />`;

    svg += `<rect x="${leftX}" y="${pairY}" width="${gridSz}" height="${gridSz}" ${getCellBorderAttrs(config, '#CBD5E1', 1.5)} />`;
    for (let i = 1; i < gridSize; i++) {
      svg += `<line x1="${leftX + i * cellSz}" y1="${pairY}" x2="${leftX + i * cellSz}" y2="${pairY + gridSz}" stroke="#E2E8F0" stroke-width="0.8" />`;
      svg += `<line x1="${leftX}" y1="${pairY + i * cellSz}" x2="${leftX + gridSz}" y2="${pairY + i * cellSz}" stroke="#E2E8F0" stroke-width="0.8" />`;
    }
    puzzle.sourceGrid.forEach((row, r) => {
      row.forEach((cell, c) => {
        if (cell) {
          const cx = leftX + c * cellSz + cellSz / 2;
          const cy = pairY + r * cellSz + cellSz / 2;
          svg += getShapeSVG(cell.shape, cx, cy, cellSz * shapeScale, getFill(cell.shape), getStroke(cell.shape), getStrokeW(), cell.rotation);
        }
      });
    });

    svg += `<rect x="${rightX}" y="${pairY}" width="${gridSz}" height="${gridSz}" ${getCellBorderAttrs(config, '#CBD5E1', 1.5)} />`;
    for (let i = 1; i < gridSize; i++) {
      svg += `<line x1="${rightX + i * cellSz}" y1="${pairY}" x2="${rightX + i * cellSz}" y2="${pairY + gridSz}" stroke="#E2E8F0" stroke-width="0.8" />`;
      svg += `<line x1="${rightX}" y1="${pairY + i * cellSz}" x2="${rightX + gridSz}" y2="${pairY + i * cellSz}" stroke="#E2E8F0" stroke-width="0.8" />`;
    }

    if (config.showAnswerKey) {
      puzzle.mirroredGrid.forEach((row, r) => {
        row.forEach((cell, c) => {
          if (cell) {
            const cx = rightX + c * cellSz + cellSz / 2;
            const cy = pairY + r * cellSz + cellSz / 2;
            svg += getShapeSVG(cell.shape, cx, cy, cellSz * shapeScale * 0.7, '#CBD5E1', '#94A3B8', 1, cell.rotation);
          }
        });
      });
    }
  });

  return svg;
}

// ========== MODE 9: FIGURE GROUND ==========
function renderFigureGroundMode(
  config: WorksheetConfig,
  data: WorksheetData,
  shapeScale: number,
  getFill: (s: ShapeName) => string,
  getStroke: (s: ShapeName) => string,
  getStrokeW: () => number,
) {
  const puzzle = data.figureGroundPuzzle!;
  const { shapes: placed, targetShapes } = puzzle;
  let svg = '';

  const refY = MARGIN + 85;
  const refH = 56;
  const boxCount = targetShapes.length;
  const totalRefW = Math.min(boxCount * 90, W - MARGIN * 2);
  const refX = (W - totalRefW) / 2;
  const boxW = totalRefW / boxCount;

  targetShapes.forEach((shape, i) => {
    const bx = refX + i * boxW + 4;
    const bw = boxW - 8;
    svg += `<rect x="${bx}" y="${refY}" width="${bw}" height="${refH}" rx="6" fill="#F8FAFC" stroke="#CBD5E1" stroke-width="1.5" />`;
    svg += getShapeSVG(shape, bx + bw / 2, refY + 24, 32, getFill(shape), getStroke(shape), getStrokeW());
    svg += `<line x1="${bx + bw * 0.25}" y1="${refY + refH - 10}" x2="${bx + bw * 0.75}" y2="${refY + refH - 10}" stroke="#94A3B8" stroke-width="1.5" />`;
  });

  const areaTop = refY + refH + 18;
  const areaH = H - areaTop - MARGIN - 35;
  const areaW = W - MARGIN * 2;
  const areaX = MARGIN;

  svg += `<rect x="${areaX}" y="${areaTop}" width="${areaW}" height="${areaH}" ${getBorderAttrs(config, '#CBD5E1', 1.5)} />`;

  const scaleX = areaW / 400;
  const scaleY = areaH / 400;

  placed.forEach(s => {
    const cx = areaX + s.cx * scaleX;
    const cy = areaTop + s.cy * scaleY;
    const r = s.r * Math.min(scaleX, scaleY);
    const raw = getShapeRawSVG(s.shape, cx, cy, r);
    const transform = s.rotation ? ` transform="rotate(${s.rotation}, ${cx}, ${cy})"` : '';
    svg += raw.replace('/>', ` fill="none" stroke="${getStroke(s.shape)}" stroke-width="2.5"${transform} />`);
  });

  if (config.showAnswerKey) {
    const answers = targetShapes.map(s => `${s}: ${puzzle.counts[s]}`).join('   ');
    svg += `<text x="${W / 2}" y="${areaTop + areaH + 14}" text-anchor="middle" font-family="Inter, sans-serif" font-size="9" fill="#94A3B8">Answers: ${answers}</text>`;
  }

  return svg;
}

// ========== MODE 10: VISUAL CLOSURE ==========
function renderClosureMode(
  config: WorksheetConfig,
  data: WorksheetData,
  shapeScale: number,
  getFill: (s: ShapeName) => string,
  getStroke: (s: ShapeName) => string,
  getStrokeW: () => number,
) {
  const puzzles = data.closurePuzzles!;
  let svg = '';

  const startY = MARGIN + 88;
  const availH = H - startY - MARGIN - 35;
  const cols = 2;
  const rows = Math.ceil(puzzles.length / cols);
  const cellW = (W - MARGIN * 2) / cols;
  const cellH = availH / rows;
  const shapeSz = Math.min(cellW * 0.4, cellH * 0.45, 70);

  puzzles.forEach((puzzle, idx) => {
    const col = idx % cols;
    const row = Math.floor(idx / cols);
    const cx = MARGIN + col * cellW + cellW / 2;
    const cy = startY + row * cellH + cellH * 0.32;

    svg += `<text x="${cx}" y="${cy - shapeSz / 2 - 10}" text-anchor="middle" font-family="Nunito, sans-serif" font-size="11" font-weight="700" fill="#64748B">${idx + 1}.</text>`;

    const raw = getShapeRawSVG(puzzle.shape, cx, cy, shapeSz);
    svg += raw.replace('/>', ` fill="none" stroke="${getStroke(puzzle.shape)}" stroke-width="3" stroke-dasharray="${puzzle.dashArray}" />`);

    const optY = cy + shapeSz / 2 + 20;
    const optSize = 24;
    const optSpacing = 42;
    const optStartX = cx - optSpacing;

    puzzle.options.forEach((opt, oIdx) => {
      const ox = optStartX + oIdx * optSpacing;
      svg += `<text x="${ox}" y="${optY - 6}" text-anchor="middle" font-family="Inter, sans-serif" font-size="8" font-weight="600" fill="#94A3B8">${String.fromCharCode(65 + oIdx)}</text>`;
      svg += getShapeSVG(opt, ox, optY + optSize / 2 + 2, optSize, getFill(opt), getStroke(opt), getStrokeW());
    });
  });

  if (config.showAnswerKey) {
    const answers = puzzles.map((p, i) => `${i + 1}→${String.fromCharCode(65 + p.correctIndex)}`).join('  ');
    svg += `<text x="${W / 2}" y="${H - MARGIN - 28}" text-anchor="middle" font-family="Inter, sans-serif" font-size="9" fill="#94A3B8">Answers: ${answers}</text>`;
  }

  return svg;
}

// ========== MODE 11: TRACE YOUR NAME ==========
function renderTraceNameMode(
  config: WorksheetConfig,
  data: WorksheetData,
) {
  const traceData = data.traceNameData!;
  if (!traceData || traceData.letters.length === 0) {
    return `<text x="${W / 2}" y="${H / 2}" text-anchor="middle" font-family="Nunito, sans-serif" font-size="16" fill="#94A3B8">Enter a name to generate tracing worksheet</text>`;
  }

  let svg = '';
  const letterH = config.difficulty === 'easy' ? 60 : config.difficulty === 'medium' ? 50 : 40;
  const letterW = letterH * 0.7;
  const startY = MARGIN + 90;
  const availH = H - startY - MARGIN - 35;

  // For each section of up to 5 letters
  const sectionCount = traceData.sections.length;
  const sectionH = availH / sectionCount;

  traceData.sections.forEach((section, sIdx) => {
    const secY = startY + sIdx * sectionH;
    const totalLetterW = section.length * (letterW + 12) - 12;
    const secStartX = (W - totalLetterW) / 2;

    // 3 rows: reference, dot-trace, blank
    const rowLabels = ['Reference', 'Trace', 'Write'];
    const rowH = Math.min(sectionH / 3 - 4, letterH + 20);

    for (let rowIdx = 0; rowIdx < 3; rowIdx++) {
      const rowY = secY + rowIdx * rowH;

      // Row label
      svg += `<text x="${MARGIN}" y="${rowY + rowH / 2 + 4}" font-family="Inter, sans-serif" font-size="8" fill="#94A3B8">${rowLabels[rowIdx]}</text>`;

      // Baseline
      svg += `<line x1="${secStartX - 5}" y1="${rowY + rowH - 4}" x2="${secStartX + totalLetterW + 5}" y2="${rowY + rowH - 4}" stroke="#E2E8F0" stroke-width="1" />`;
      // Midline (dashed)
      svg += `<line x1="${secStartX - 5}" y1="${rowY + rowH - 4 - letterH / 2}" x2="${secStartX + totalLetterW + 5}" y2="${rowY + rowH - 4 - letterH / 2}" stroke="#E2E8F0" stroke-width="0.5" stroke-dasharray="4,4" />`;
      // Topline
      svg += `<line x1="${secStartX - 5}" y1="${rowY + rowH - 4 - letterH}" x2="${secStartX + totalLetterW + 5}" y2="${rowY + rowH - 4 - letterH}" stroke="#E2E8F0" stroke-width="0.5" />`;

      section.forEach((letter, lIdx) => {
        const lx = secStartX + lIdx * (letterW + 12);
        const ly = rowY + rowH - 4 - letterH; // top of letter area
        const strokes = LETTER_PATHS[letter];
        if (!strokes) return;

        if (rowIdx === 0) {
          // Reference: solid light grey letter
          strokes.forEach(stroke => {
            if (stroke.length < 2) return;
            const points = stroke.map(([px, py]: StrokePoint) =>
              `${lx + px * letterW},${ly + py * letterH}`
            ).join(' ');
            svg += `<polyline points="${points}" fill="none" stroke="#CBD5E1" stroke-width="3" stroke-linecap="round" stroke-linejoin="round" />`;
          });
        } else if (rowIdx === 1) {
          // Dot-trace: dots along the stroke path
          strokes.forEach((stroke, strokeIdx) => {
            if (stroke.length < 2) return;
            // Draw dots along the path
            const dotSpacing = config.difficulty === 'easy' ? 6 : config.difficulty === 'medium' ? 8 : 10;
            const dotR = config.difficulty === 'easy' ? 2.5 : 2;

            // Interpolate points along each segment
            for (let si = 0; si < stroke.length - 1; si++) {
              const [x1, y1] = stroke[si];
              const [x2, y2] = stroke[si + 1];
              const segLen = Math.sqrt((x2 - x1) ** 2 + (y2 - y1) ** 2) * letterW;
              const dots = Math.max(2, Math.ceil(segLen / dotSpacing));

              for (let d = 0; d <= dots; d++) {
                const t = d / dots;
                const dx = lx + (x1 + (x2 - x1) * t) * letterW;
                const dy = ly + (y1 + (y2 - y1) * t) * letterH;
                svg += `<circle cx="${dx}" cy="${dy}" r="${dotR}" fill="#94A3B8" />`;
              }
            }

            // Starting dot (large green) for first stroke
            if (strokeIdx === 0) {
              const [sx, sy] = stroke[0];
              const startX = lx + sx * letterW;
              const startY2 = ly + sy * letterH;
              svg += `<circle cx="${startX}" cy="${startY2}" r="4.5" fill="#22C55E" />`;

              // Arrow showing direction
              if (stroke.length >= 2) {
                const [nx, ny] = stroke[1];
                const endX = lx + nx * letterW;
                const endY = ly + ny * letterH;
                const angle = Math.atan2(endY - startY2, endX - startX);
                const arrowLen = 10;
                const ax = startX + Math.cos(angle) * arrowLen;
                const ay = startY2 + Math.sin(angle) * arrowLen;
                svg += `<line x1="${startX}" y1="${startY2}" x2="${ax}" y2="${ay}" stroke="#22C55E" stroke-width="1.5" />`;
                svg += `<polygon points="${ax},${ay} ${ax - 4 * Math.cos(angle - 0.5)},${ay - 4 * Math.sin(angle - 0.5)} ${ax - 4 * Math.cos(angle + 0.5)},${ay - 4 * Math.sin(angle + 0.5)}" fill="#22C55E" />`;
              }
            }
          });
        }
        // rowIdx === 2: blank row, just the guidelines (already drawn above)
      });
    }
  });

  return svg;
}

// ========== MODE 12: HANDWRITING PRACTICE ==========

function isChinese(ch: string): boolean {
  const code = ch.charCodeAt(0);
  return code >= 0x4e00 && code <= 0x9fff;
}

function hasChinese(text: string): boolean {
  return Array.from(text).some(isChinese);
}

function isAllChinese(text: string): boolean {
  return Array.from(text).every(ch => isChinese(ch) || ch === ' ');
}

// Letter classification for adaptive box heights
const ASCENDERS = new Set('bdfhklt'.split(''));
const DESCENDERS = new Set('gjpqy'.split(''));
const CAPITALS = new Set('ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split(''));

function getLetterType(ch: string): 'tall' | 'medium' | 'descender' {
  if (CAPITALS.has(ch) || ASCENDERS.has(ch)) return 'tall';
  if (DESCENDERS.has(ch)) return 'descender';
  return 'medium';
}

// Line color hex mapping
const LINE_COLOR_MAP: Record<string, string> = {
  red: '#DC2626', blue: '#2563EB', green: '#16A34A', purple: '#9333EA', black: '#1E293B',
};
const LINE_MID_MAP: Record<string, string> = {
  red: '#F9A8D4', blue: '#93C5FD', green: '#86EFAC', purple: '#C4B5FD', black: '#94A3B8',
};
const HIGHLIGHT_SKY_MAP: Record<string, string> = {
  blue: '#DBEAFE', yellow: '#FEF9C3', green: '#DCFCE7', pink: '#FCE7F3', none: '',
};
const HIGHLIGHT_GRASS_MAP: Record<string, string> = {
  blue: '#DCFCE7', yellow: '#FEF3C7', green: '#D1FAE5', pink: '#FDF2F8', none: '',
};

// Colored tri-line set (HWT-style) anchored to text baseline
function renderColoredTrilineSet(
  x: number, baselineY: number, fontPx: number, width: number, config: WorksheetConfig
): string {
  const capHeight = fontPx * 0.7;
  const xHeight = fontPx * 0.5;
  const topY = baselineY - capHeight;
  const midY = baselineY - xHeight;
  const botY = baselineY;
  const skyH = capHeight * 0.2;
  const grassH = capHeight * 0.15;

  const useColor = config.handwritingShowColoredLines;
  const lineColor = useColor ? (LINE_COLOR_MAP[config.handwritingLineColor] || '#DC2626') : '#94A3B8';
  const midColor = useColor ? (LINE_MID_MAP[config.handwritingLineColor] || '#F9A8D4') : '#CBD5E1';
  const showHighlight = config.handwritingShowHighlight;
  const hlColor = config.handwritingHighlightColor || 'blue';

  let svg = '';

  if (showHighlight && hlColor !== 'none') {
    const skyFill = HIGHLIGHT_SKY_MAP[hlColor] || '#DBEAFE';
    const grassFill = HIGHLIGHT_GRASS_MAP[hlColor] || '#DCFCE7';
    svg += `<rect x="${x}" y="${topY - skyH}" width="${width}" height="${skyH}" fill="${skyFill}" opacity="0.6" />`;
    svg += `<rect x="${x}" y="${botY}" width="${width}" height="${grassH}" fill="${grassFill}" opacity="0.5" />`;
  }

  svg += `<line x1="${x}" y1="${topY}" x2="${x + width}" y2="${topY}" stroke="${lineColor}" stroke-width="1.2" />`;
  svg += `<line x1="${x}" y1="${midY}" x2="${x + width}" y2="${midY}" stroke="${midColor}" stroke-width="0.8" stroke-dasharray="4 3" />`;
  svg += `<line x1="${x}" y1="${botY}" x2="${x + width}" y2="${botY}" stroke="${lineColor}" stroke-width="1.2" />`;

  return svg;
}

// Render text on tri-lines — text y = baselineY exactly
function renderTextOnTriline(
  chars: string[], x: number, baselineY: number, fontPx: number, contentW: number,
  fontFamily: string, color: string, isDottedTrace: boolean
): string {
  if (chars.length === 0) return '';
  const charW = Math.min(fontPx * 0.62, contentW / Math.max(chars.length, 1));
  let svg = '';
  for (let c = 0; c < chars.length; c++) {
    const cx = x + 4 + c * charW + charW / 2;
    if (cx > x + contentW) break;
    if (isDottedTrace) {
      svg += `<text x="${cx}" y="${baselineY}" text-anchor="middle" font-family="${fontFamily}" font-size="${fontPx}" font-weight="400" fill="none" stroke="#94A3B8" stroke-width="1" stroke-dasharray="2.5 2">${escapeXml(chars[c])}</text>`;
    } else {
      svg += `<text x="${cx}" y="${baselineY}" text-anchor="middle" font-family="${fontFamily}" font-size="${fontPx}" font-weight="500" fill="${color}">${escapeXml(chars[c])}</text>`;
    }
  }
  return svg;
}

// Sentence mode: 3-row groups (reference / trace / blank) with colored tri-lines
// lineH here = the raw mm-based size used as fontPx for the trace text
function renderSentenceTrilineMode(
  text: string, rows: number, startY: number, availableH: number,
  lineH: number, contentW: number, fontFamily: string, config: WorksheetConfig
): string {
  const mmToPx = 2.833;
  const fontPx = lineH; // lineH in px IS the font size
  const capHeight = fontPx * 0.7;
  const grassH = capHeight * 0.15;
  const triSetH = capHeight + grassH; // total visual height of one tri-line set
  const groupGap = 12 * mmToPx;
  const setGap = 6 * mmToPx;
  const refTextH = Math.max(fontPx * 0.85, 10 * mmToPx + refFontPx); // min 10mm gap between ref text bottom and top line
  const groupH = refTextH + triSetH + setGap + triSetH + groupGap;
  const maxGroups = Math.min(rows, Math.floor(availableH / groupH));
  const allChars = Array.from(text);
  let svg = '';

  for (let g = 0; g < maxGroups; g++) {
    const groupY = startY + g * groupH;

    // Row 1: Reference text in solid black above the tri-line
    const refFontPx = fontPx * 0.55;
    const charW = Math.min(refFontPx * 0.62, contentW / Math.max(allChars.length, 1));
    for (let c = 0; c < allChars.length; c++) {
      const cx = MARGIN + 4 + c * charW + charW / 2;
      if (cx > W - MARGIN) break;
      svg += `<text x="${cx}" y="${groupY + refTextH * 0.85}" text-anchor="middle" font-family="${fontFamily}" font-size="${refFontPx}" font-weight="600" fill="#1E293B">${escapeXml(allChars[c])}</text>`;
    }

    // Row 2: Dotted trace on colored tri-lines
    // baseline sits at top of group + refTextH + capHeight (so cap tops touch top line)
    const traceBaselineY = groupY + refTextH + capHeight;
    svg += renderColoredTrilineSet(MARGIN, traceBaselineY, fontPx, contentW, config);
    svg += renderTextOnTriline(allChars, MARGIN, traceBaselineY, fontPx, contentW, fontFamily, '#94A3B8', true);

    // Row 3: Blank colored tri-lines for independent writing
    const blankBaselineY = traceBaselineY + grassH + setGap + capHeight;
    svg += renderColoredTrilineSet(MARGIN, blankBaselineY, fontPx, contentW, config);
  }

  return svg;
}

function renderGridBoxRows(
  chars: string[], rows: number, startY: number, availableH: number,
  boxSize: number, gapBetweenSets: number, contentW: number,
  fontFamily: string, isDotted: boolean, ghostColor: string, config: WorksheetConfig,
  sectionLabel?: string
): { svg: string; usedH: number } {
  const rowH = boxSize + gapBetweenSets * 0.5;
  const maxRows = Math.min(rows, Math.floor(availableH / rowH));
  const maxCols = Math.floor(contentW / boxSize);
  const charCount = Math.min(chars.length, maxCols);
  let svg = '';

  if (sectionLabel) {
    svg += `<text x="${MARGIN}" y="${startY - 4}" font-family="Nunito, sans-serif" font-size="11" font-weight="700" fill="#64748B">${escapeXml(sectionLabel)}</text>`;
  }

  for (let r = 0; r < maxRows; r++) {
    const baseY = startY + r * rowH;
    for (let c = 0; c < charCount; c++) {
      const bx = MARGIN + c * boxSize;
      const borderAttrs = getCellBorderAttrs(config, '#94A3B8', 1);
      svg += `<rect x="${bx}" y="${baseY}" width="${boxSize}" height="${boxSize}" ${borderAttrs} />`;

      if (r === 0) {
        const ch = chars[c];
        const charFontPx = boxSize * 0.65;
        if (isDotted) {
          svg += `<text x="${bx + boxSize / 2}" y="${baseY + boxSize * 0.72}" text-anchor="middle" font-family="${fontFamily}" font-size="${charFontPx}" font-weight="400" fill="none" stroke="${ghostColor}" stroke-width="0.8" stroke-dasharray="2 2">${escapeXml(ch)}</text>`;
        } else {
          svg += `<text x="${bx + boxSize / 2}" y="${baseY + boxSize * 0.72}" text-anchor="middle" font-family="${fontFamily}" font-size="${charFontPx}" font-weight="400" fill="${ghostColor}">${escapeXml(ch)}</text>`;
        }
      }
    }
  }
  return { svg, usedH: maxRows * rowH };
}

// ========== WORD BOXES SUB-MODE ==========
function renderWordBoxesMode(config: WorksheetConfig, data: WorksheetData): string {
  if (!data.handwritingData) return '';
  const { words, fontSizeMm, font } = data.handwritingData;
  if (words.length === 0) return '';

  const mmToPx = 2.833;
  const fontFamilyMap: Record<string, string> = {
    print: "Arial, Helvetica, sans-serif",
    cursive: "'Segoe Script', 'Comic Sans MS', cursive",
    manuscript: "'Courier New', Courier, monospace",
    dotted: "Arial, sans-serif",
  };
  const fontFamily = fontFamilyMap[font] || fontFamilyMap.print;

  const contentW = W - MARGIN * 2;
  const startY = MARGIN + 90;
  const availableH = H - startY - MARGIN - 30;
  const colW = (contentW - 20) / 2; // 2 columns with 20px gap
  const lineH = fontSizeMm * mmToPx;

  // Sizing
  const tallH = Math.max(25 * mmToPx, lineH);
  const medH = Math.max(18 * mmToPx, lineH * 0.72);
  const descH = tallH; // same height but with extra below baseline
  const descExtra = 7 * mmToPx; // extra space below baseline for descenders
  const labelH = 16; // label text height
  const trilineSetH = lineH; // tri-line trace height
  const gapBetweenParts = 6 * mmToPx;
  const wordBlockH = labelH + trilineSetH + gapBetweenParts + tallH + descExtra + gapBetweenParts;
  const maxPerCol = Math.min(4, Math.floor(availableH / wordBlockH));

  let svg = '';

  words.slice(0, maxPerCol * 2).forEach((word, wIdx) => {
    const col = wIdx % 2;
    const row = Math.floor(wIdx / 2);
    if (row >= maxPerCol) return;

    const colX = MARGIN + col * (colW + 20);
    const blockY = startY + row * wordBlockH;
    const chars = Array.from(word.trim());
    if (chars.length === 0) return;

    // 1. Word label in black
    svg += `<text x="${colX}" y="${blockY + 12}" font-family="${fontFamily}" font-size="13" font-weight="700" fill="#1E293B">${escapeXml(word.trim())}</text>`;

    // 2. Tri-line trace with colored lines — baseline-anchored
    const fontPxTrace = lineH;
    const capH = fontPxTrace * 0.7;
    const grassH = capH * 0.15;
    const traceBaselineY = blockY + labelH + capH;
    svg += renderColoredTrilineSet(colX, traceBaselineY, fontPxTrace, colW, config);
    svg += renderTextOnTriline(chars, colX, traceBaselineY, fontPxTrace, colW, fontFamily, '#94A3B8', true);

    // 3. Adaptive word boxes
    const boxesY = traceBaselineY + grassH + gapBetweenParts;
    const boxW = Math.min(colW / chars.length, tallH * 0.8); // uniform width
    const baseline = boxesY + tallH; // shared baseline

    chars.forEach((ch, cIdx) => {
      const bx = colX + cIdx * boxW;
      const type = getLetterType(ch);
      let boxTop: number;
      let boxHeight: number;

      if (type === 'tall') {
        boxTop = boxesY;
        boxHeight = tallH;
      } else if (type === 'descender') {
        boxTop = baseline - medH;
        boxHeight = medH + descExtra;
      } else {
        boxTop = baseline - medH;
        boxHeight = medH;
      }

      // Thick black border box
      svg += `<rect x="${bx}" y="${boxTop}" width="${boxW}" height="${boxHeight}" fill="none" stroke="#1E293B" stroke-width="1.8" rx="2" />`;

      // Baseline indicator (thin line across all boxes)
      if (cIdx === 0) {
        svg += `<line x1="${colX}" y1="${baseline}" x2="${colX + chars.length * boxW}" y2="${baseline}" stroke="#DC2626" stroke-width="0.6" stroke-dasharray="3 2" />`;
      }
    });
  });

  return svg;
}

function renderHandwritingMode(config: WorksheetConfig, data: WorksheetData): string {
  if (!data.handwritingData) return '';
  const { text, rows, paperStyle, fontSizeMm, font, subMode } = data.handwritingData;

  // Word Boxes sub-mode
  if (subMode === 'wordBoxes') {
    return renderWordBoxesMode(config, data);
  }

  const mmToPx = 2.833;
  const lineH = fontSizeMm * mmToPx;
  const boxSize = fontSizeMm * mmToPx;
  const gapBetweenSets = 8 * mmToPx;
  const contentW = W - MARGIN * 2;
  const startY = MARGIN + 90;
  const availableH = H - startY - MARGIN - 30;

  const fontFamilyMap: Record<string, string> = {
    print: "Arial, Helvetica, sans-serif",
    cursive: "'Segoe Script', 'Comic Sans MS', cursive",
    manuscript: "'Courier New', Courier, monospace",
    dotted: "Arial, sans-serif",
  };
  const fontFamily = fontFamilyMap[font] || fontFamilyMap.print;
  const ghostColor = '#C8CDD3';
  const isDotted = font === 'dotted';
  const allChars = Array.from(text);

  let svg = '';

  const containsChinese = hasChinese(text);
  const allChinese = isAllChinese(text);

  // Determine rendering strategy based on content + paper style
  if (paperStyle === 'gridbox') {
    const result = renderGridBoxRows(allChars, rows, startY, availableH, boxSize, gapBetweenSets, contentW, fontFamily, isDotted, ghostColor, config);
    svg += result.svg;
  } else if (paperStyle === 'both') {
    if (allChinese) {
      const result = renderGridBoxRows(allChars, rows, startY, availableH, boxSize, gapBetweenSets, contentW, fontFamily, isDotted, ghostColor, config, 'Grid Box Paper (方格紙)');
      svg += result.svg;
    } else if (containsChinese) {
      const engChars = allChars.filter(ch => !isChinese(ch));
      const chnChars = allChars.filter(isChinese);
      const halfH = availableH * 0.48;
      // English tri-line (colored) at top
      svg += renderSentenceTrilineMode(engChars.join(''), Math.max(1, Math.floor(rows / 2)), startY, halfH, lineH, contentW, fontFamily, config);
      const gridStartY = startY + availableH * 0.52;
      const gridResult = renderGridBoxRows(chnChars, Math.max(1, Math.ceil(rows / 2)), gridStartY, halfH, boxSize, gapBetweenSets, contentW, fontFamily, isDotted, ghostColor, config, 'Grid Box Paper (方格紙)');
      svg += gridResult.svg;
    } else {
      const halfH = availableH * 0.48;
      svg += renderSentenceTrilineMode(text, Math.max(1, Math.floor(rows / 2)), startY, halfH, lineH, contentW, fontFamily, config);
      const gridStartY = startY + availableH * 0.52;
      const gridResult = renderGridBoxRows(allChars, Math.max(1, Math.ceil(rows / 2)), gridStartY, halfH, boxSize, gapBetweenSets, contentW, fontFamily, isDotted, ghostColor, config, 'Grid Box Paper (方格紙)');
      svg += gridResult.svg;
    }
  } else {
    // Tri-line mode — now uses colored HWT-style lines with sentence groups
    if (allChinese) {
      // Chinese: first row grid boxes, remaining blank colored tri-lines
      const rowH = boxSize + gapBetweenSets * 0.5;
      const maxCols = Math.floor(contentW / boxSize);
      const charCount = Math.min(allChars.length, maxCols);

      for (let c = 0; c < charCount; c++) {
        const bx = MARGIN + c * boxSize;
        const borderAttrs = getCellBorderAttrs(config, '#94A3B8', 1);
        svg += `<rect x="${bx}" y="${startY}" width="${boxSize}" height="${boxSize}" ${borderAttrs} />`;
        const ch = allChars[c];
        const charFontPx = boxSize * 0.65;
        svg += `<text x="${bx + boxSize / 2}" y="${startY + boxSize * 0.72}" text-anchor="middle" font-family="${fontFamily}" font-size="${charFontPx}" font-weight="400" fill="${ghostColor}">${escapeXml(ch)}</text>`;
      }

      // Blank colored tri-lines below
      const triStartY = startY + rowH;
      const remainH = availableH - rowH;
      const fontPxBlank = lineH;
      const capHBlank = fontPxBlank * 0.7;
      const grassHBlank = capHBlank * 0.15;
      const triSetHBlank = capHBlank + grassHBlank;
      const setGap = 4 * mmToPx;
      const setH = triSetHBlank + setGap;
      const blankRows = Math.min(rows - 1, Math.floor(remainH / setH));
      for (let r = 0; r < blankRows; r++) {
        const blankBaselineY = triStartY + r * setH + capHBlank;
        svg += renderColoredTrilineSet(MARGIN, blankBaselineY, fontPxBlank, contentW);
      }
    } else if (containsChinese) {
      const engChars = allChars.filter(ch => !isChinese(ch));
      const chnChars = allChars.filter(isChinese);
      const rowH = boxSize + gapBetweenSets * 0.5;
      const maxCols = Math.floor(contentW / boxSize);
      const charCount = Math.min(chnChars.length, maxCols);

      svg += `<text x="${MARGIN}" y="${startY - 4}" font-family="Nunito, sans-serif" font-size="11" font-weight="700" fill="#64748B">Chinese — Grid Box (方格紙)</text>`;
      for (let c = 0; c < charCount; c++) {
        const bx = MARGIN + c * boxSize;
        const borderAttrs = getCellBorderAttrs(config, '#94A3B8', 1);
        svg += `<rect x="${bx}" y="${startY}" width="${boxSize}" height="${boxSize}" ${borderAttrs} />`;
        const charFontPx = boxSize * 0.65;
        svg += `<text x="${bx + boxSize / 2}" y="${startY + boxSize * 0.72}" text-anchor="middle" font-family="${fontFamily}" font-size="${charFontPx}" font-weight="400" fill="${ghostColor}">${escapeXml(chnChars[c])}</text>`;
      }

      const triStartY = startY + rowH + gapBetweenSets * 0.5;
      const remainH = availableH - rowH - gapBetweenSets * 0.5;
      svg += renderSentenceTrilineMode(engChars.join(''), Math.max(1, rows - 1), triStartY, remainH, lineH, contentW, fontFamily, config);
    } else {
      // Pure English: colored tri-line with 3-row sentence groups
      svg += renderSentenceTrilineMode(text, rows, startY, availableH, lineH, contentW, fontFamily, config);
    }
  }

  return svg;
}

function escapeXml(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&apos;');
}
