import { useEffect, useRef, useState } from 'react';
import { WorksheetConfig, WorksheetData, ShapeName, SHAPE_COLORS, getShapeSVG, getShapeRawSVG } from '@/lib/shapes';
import { LETTER_PATHS, StrokePoint } from '@/lib/letterPaths';

interface Props {
  config: WorksheetConfig;
  data: WorksheetData;
}

// Trace overlay data: collected during SVG generation, rendered as HTML divs
interface TraceOverlay {
  text: string;
  x: number;
  y: number;
  fontPx: number;
  width: number;
}

let _traceOverlays: TraceOverlay[] = [];

const W = 595;
const H = 842;
const MARGIN = 40;
const BW_FILL = 'none';
const BW_STROKE = '#1E293B';

// Border style helpers
function getBorderAttrs(config: WorksheetConfig, strokeColor = '#CBD5E1', width = 1.5): string {
  const dash = config.borderStyle === 'dotted' ? ` stroke-dasharray="4 4"` : '';
  const rx = config.borderStyle === 'rounded' ? ` rx="8" ry="8"` : ` rx="3"`;
  return `fill="none" stroke="${strokeColor}" stroke-width="${width}"${dash}${rx}`;
}

function getCellBorderAttrs(config: WorksheetConfig, strokeColor = '#CBD5E1', width = 1): string {
  const dash = config.borderStyle === 'dotted' ? ` stroke-dasharray="4 4"` : '';
  const rx = config.borderStyle === 'rounded' ? ` rx="6" ry="6"` : ` rx="3"`;
  return `fill="none" stroke="${strokeColor}" stroke-width="${width}"${dash}${rx}`;
}

export default function WorksheetPreview({ config, data }: Props) {
  const getFill = (shape: ShapeName) => config.useColor ? SHAPE_COLORS[shape] : BW_FILL;
  const getStroke = (shape: ShapeName) => config.useColor ? SHAPE_COLORS[shape] : BW_STROKE;
  const getStrokeW = () => config.useColor ? 1.5 : 2.5;

  const shapeScale = config.difficulty === 'easy' ? 1.15 : config.difficulty === 'medium' ? 1.0 : 0.85;

  const containerRef = useRef<HTMLDivElement | null>(null);
  const [overlayScale, setOverlayScale] = useState({ x: 1, y: 1 });

  useEffect(() => {
    const el = containerRef.current;
    if (!el) return;

    const updateScale = () => {
      const rect = el.getBoundingClientRect();
      if (rect.width > 0 && rect.height > 0) {
        setOverlayScale({ x: rect.width / W, y: rect.height / H });
      }
    };

    updateScale();
    const ro = new ResizeObserver(updateScale);
    ro.observe(el);

    return () => ro.disconnect();
  }, []);

  // Header font sizes
  const nameFontSize = config.nameDateFontSize === 'small' ? 12 : config.nameDateFontSize === 'large' ? 20 : 16;
  const dateFontSize = config.nameDateFontSize === 'small' ? 9 : config.nameDateFontSize === 'large' ? 14 : 11;
  const nameWeight = config.headerBold ? '800' : '600';
  const ageStr = config.childAge !== null ? ` (Age ${config.childAge})` : '';
  const nameStr = config.childName ? config.childName + ageStr : '___________________';

  const instrFontSize = config.instructionFontSize === 'small' ? 11 : config.instructionFontSize === 'large' ? 18 : 14;
  const instrWeight = config.instructionBold ? '800' : '700';

  const headerSVG = `
    <text x="${W / 2}" y="${MARGIN + 22}" text-anchor="middle" font-family="Nunito, sans-serif" font-size="20" font-weight="800" fill="#0D9488">OTsheet.ai</text>
    <line x1="${MARGIN}" y1="${MARGIN + 32}" x2="${W - MARGIN}" y2="${MARGIN + 32}" stroke="#E2E8F0" stroke-width="1" />
    <text x="${MARGIN}" y="${MARGIN + 52}" font-family="Nunito, sans-serif" font-size="${nameFontSize}" font-weight="${nameWeight}" fill="#334155">Name: ${nameStr}</text>
    <text x="${W - MARGIN}" y="${MARGIN + 52}" text-anchor="end" font-family="Inter, sans-serif" font-size="${dateFontSize}" fill="#94A3B8">Date: ____/____/________</text>
    <text x="${W / 2}" y="${MARGIN + 72}" text-anchor="middle" font-family="Nunito, sans-serif" font-size="${instrFontSize}" font-weight="${instrWeight}" fill="#1E293B">${data.instructions}</text>
  `;

  const footerSVG = `
    <line x1="${MARGIN}" y1="${H - MARGIN - 20}" x2="${W - MARGIN}" y2="${H - MARGIN - 20}" stroke="#E2E8F0" stroke-width="1" />
    <text x="${MARGIN}" y="${H - MARGIN - 4}" font-family="Inter, sans-serif" font-size="10" font-weight="600" fill="#94A3B8">Skill: ${data.skillLabel}</text>
    <text x="${W - MARGIN}" y="${H - MARGIN - 4}" text-anchor="end" font-family="Inter, sans-serif" font-size="9" fill="#CBD5E1">Generated by OTsheet.ai</text>
  `;

  // Collect trace overlays during SVG generation
  _traceOverlays = [];

  let bodySVG = '';

  if (data.mode === 'find') {
    bodySVG = renderFindMode(config, data, shapeScale, getFill, getStroke, getStrokeW);
  } else if (data.mode === 'missing') {
    bodySVG = renderMissingMode(config, data, shapeScale, getFill, getStroke, getStrokeW);
  } else if (data.mode === 'pattern') {
    bodySVG = renderPatternMode(config, data, shapeScale, getFill, getStroke, getStrokeW);
  } else if (data.mode === 'count') {
    bodySVG = renderCountMode(config, data, shapeScale, getFill, getStroke, getStrokeW);
  } else if (data.mode === 'copy') {
    bodySVG = renderCopyMode(config, data, shapeScale, getFill, getStroke, getStrokeW);
  } else if (data.mode === 'sequence') {
    bodySVG = renderSequenceMode(config, data, shapeScale, getFill, getStroke, getStrokeW);
  } else if (data.mode === 'oddOneOut') {
    bodySVG = renderOddOneOutMode(config, data, shapeScale, getFill, getStroke, getStrokeW);
  } else if (data.mode === 'mirror') {
    bodySVG = renderMirrorMode(config, data, shapeScale, getFill, getStroke, getStrokeW);
  } else if (data.mode === 'figureGround') {
    bodySVG = renderFigureGroundMode(config, data, shapeScale, getFill, getStroke, getStrokeW);
  } else if (data.mode === 'closure') {
    bodySVG = renderClosureMode(config, data, shapeScale, getFill, getStroke, getStrokeW);
  } else if (data.mode === 'handwriting' || data.mode === 'traceName') {
    bodySVG = renderHandwritingMode(config, data);
  } else if (data.mode === 'maze') {
    bodySVG = renderMazeMode(config, data);
  } else if (data.mode === 'connectDots') {
    bodySVG = renderConnectDotsMode(config, data);
  } else if (data.mode === 'tracingPaths') {
    bodySVG = renderTracingPathsMode(config, data);
  } else if (data.mode === 'scissorSkills') {
    bodySVG = renderScissorSkillsMode(config, data);
  } else if (data.mode === 'colorByNumber') {
    bodySVG = renderColorByNumberMode(config, data);
  } else if (data.mode === 'gridDesigns') {
    bodySVG = renderGridDesignsMode(config, data);
  } else if (data.mode === 'dotArt') {
    bodySVG = renderDotArtMode(config, data);
  } else if (data.mode === 'shapeTracing') {
    bodySVG = renderShapeTracingMode(config, data);
  } else if (data.mode === 'spotDifference') {
    bodySVG = renderSpotDifferenceMode(config, data);
  } else if (data.mode === 'visualScanning') {
    bodySVG = renderVisualScanningMode(config, data);
  } else if (data.mode === 'pixelArt') {
    bodySVG = renderPixelArtMode(config, data);
  }


  const svgContent = `
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H}" width="100%" height="100%">
      <rect width="${W}" height="${H}" fill="white" rx="4" />
      ${headerSVG}
      ${bodySVG}
      ${footerSVG}
    </svg>
  `;

  const overlays = [..._traceOverlays];

  return (
    <div
      id="worksheet-preview"
      ref={containerRef}
      className="bg-card rounded-xl shadow-lg border border-border"
      style={{ aspectRatio: '210/297', maxHeight: '85vh', position: 'relative', overflow: 'hidden' }}
    >
      <div dangerouslySetInnerHTML={{ __html: svgContent }} style={{ width: '100%', height: '100%' }} />

      <div
        style={{
          position: 'absolute',
          inset: 0,
          width: W,
          height: H,
          transform: `scale(${overlayScale.x}, ${overlayScale.y})`,
          transformOrigin: 'top left',
          pointerEvents: 'none',
          zIndex: 10,
        }}
      >
        {overlays.map((o, i) => (
          <div
            key={i}
            style={{
              position: 'absolute',
              left: o.x,
              top: o.y,
              width: o.width,
              fontFamily: "'Edu AU VIC WA NT Dots', cursive",
              fontSize: o.fontPx,
              color: '#aaaaaa',
              lineHeight: 1,
              letterSpacing: '0.05em',
              whiteSpace: 'nowrap',
            }}
          >
            {o.text}
          </div>
        ))}
      </div>
    </div>
  );
}

// ========== MODE 1: FIND THE SHAPE ==========
function renderFindMode(
  config: WorksheetConfig,
  data: WorksheetData,
  shapeScale: number,
  getFill: (s: ShapeName) => string,
  getStroke: (s: ShapeName) => string,
  getStrokeW: () => number,
) {
  const targetShape = data.targetShape!;
  const grid = data.grid!;
  const size = config.gridSize;

  const refBoxY = MARGIN + 85;
  const refBoxH = 64;
  const refBoxW = 200;
  const refBoxX = (W - refBoxW) / 2;

  let svg = '';
  svg += `<rect x="${refBoxX}" y="${refBoxY}" width="${refBoxW}" height="${refBoxH}" rx="8" fill="none" stroke="#94A3B8" stroke-width="2" stroke-dasharray="8,5" />`;
  svg += `<text x="${refBoxX + 12}" y="${refBoxY + 16}" font-family="Inter, sans-serif" font-size="10" fill="#64748B">Find this shape:</text>`;
  svg += getShapeSVG(targetShape, refBoxX + refBoxW / 2, refBoxY + refBoxH / 2 + 5, 50 * shapeScale, getFill(targetShape), getStroke(targetShape), getStrokeW());

  const gridTop = refBoxY + refBoxH + 20;
  const gridAreaH = H - gridTop - MARGIN - 35;
  const gridAreaW = W - MARGIN * 2;
  const cellSize = Math.min(gridAreaW / size, gridAreaH / size);
  const gridW = cellSize * size;
  const gridH = cellSize * size;
  const gridX = (W - gridW) / 2;

  svg += `<rect x="${gridX}" y="${gridTop}" width="${gridW}" height="${gridH}" ${getBorderAttrs(config, '#CBD5E1', 2)} />`;

  if (config.showGridLines) {
    for (let i = 1; i < size; i++) {
      svg += `<line x1="${gridX + i * cellSize}" y1="${gridTop}" x2="${gridX + i * cellSize}" y2="${gridTop + gridH}" stroke="#E2E8F0" stroke-width="1" />`;
      svg += `<line x1="${gridX}" y1="${gridTop + i * cellSize}" x2="${gridX + gridW}" y2="${gridTop + i * cellSize}" stroke="#E2E8F0" stroke-width="1" />`;
    }
  }

  grid.forEach((row, r) => {
    row.forEach((cell, c) => {
      const cx = gridX + c * cellSize + cellSize / 2;
      const cy = gridTop + r * cellSize + cellSize / 2;
      svg += getShapeSVG(cell.shape, cx, cy, cellSize * shapeScale, getFill(cell.shape), getStroke(cell.shape), getStrokeW(), cell.rotation);
    });
  });

  if (config.showAnswerKey) {
    let count = 0;
    grid.forEach(row => row.forEach(cell => { if (cell.isTarget) count++; }));
    svg += `<text x="${W / 2}" y="${gridTop + gridH + 18}" text-anchor="middle" font-family="Inter, sans-serif" font-size="10" fill="#94A3B8">Answer: ${count} ${targetShape}${count !== 1 ? 's' : ''}</text>`;
  }

  return svg;
}

// ========== MODE 2: MISSING SHAPE ==========
function renderMissingMode(
  config: WorksheetConfig,
  data: WorksheetData,
  shapeScale: number,
  getFill: (s: ShapeName) => string,
  getStroke: (s: ShapeName) => string,
  getStrokeW: () => number,
) {
  const refShapes = data.referenceShapes!;
  const puzzles = data.missingPuzzles!;

  let svg = '';

  const refY = MARGIN + 85;
  const refH = 56;
  const refW = Math.min(refShapes.length * 80, W - MARGIN * 2);
  const refX = (W - refW) / 2;
  const refCellW = refW / refShapes.length;

  svg += `<rect x="${refX}" y="${refY}" width="${refW}" height="${refH}" rx="8" fill="#F8FAFC" stroke="#E2E8F0" stroke-width="1.5" />`;
  svg += `<text x="${W / 2}" y="${refY - 6}" text-anchor="middle" font-family="Inter, sans-serif" font-size="10" fill="#64748B">Reference Shapes:</text>`;

  refShapes.forEach((shape, i) => {
    const cx = refX + i * refCellW + refCellW / 2;
    const cy = refY + refH / 2;
    svg += getShapeSVG(shape, cx, cy, 42, getFill(shape), getStroke(shape), getStrokeW());
    svg += `<text x="${cx}" y="${cy + 28}" text-anchor="middle" font-family="Inter, sans-serif" font-size="8" fill="#94A3B8">${shape}</text>`;
  });

  const puzzleTop = refY + refH + 24;
  const availH = H - puzzleTop - MARGIN - 35;
  const cols = puzzles.length <= 3 ? puzzles.length : Math.min(3, puzzles.length);
  const rows = Math.ceil(puzzles.length / cols);
  const puzzleAreaW = W - MARGIN * 2;
  const puzzleCellW = puzzleAreaW / cols;
  const puzzleCellH = availH / rows;
  const subGridMaxSize = Math.min(puzzleCellW - 30, puzzleCellH - 30, 130);

  puzzles.forEach((puzzle, idx) => {
    const col = idx % cols;
    const row = Math.floor(idx / cols);
    const pSize = puzzle.grid.length;
    const cellSz = subGridMaxSize / pSize;
    const px = MARGIN + col * puzzleCellW + (puzzleCellW - subGridMaxSize) / 2;
    const py = puzzleTop + row * puzzleCellH + (puzzleCellH - subGridMaxSize) / 2;

    svg += `<text x="${px + subGridMaxSize / 2}" y="${py - 6}" text-anchor="middle" font-family="Nunito, sans-serif" font-size="11" font-weight="700" fill="#64748B">${idx + 1}.</text>`;
    svg += `<rect x="${px}" y="${py}" width="${subGridMaxSize}" height="${subGridMaxSize}" ${getCellBorderAttrs(config, '#CBD5E1', 1.5)} />`;

    if (config.showGridLines) {
      for (let i = 1; i < pSize; i++) {
        svg += `<line x1="${px + i * cellSz}" y1="${py}" x2="${px + i * cellSz}" y2="${py + subGridMaxSize}" stroke="#E2E8F0" stroke-width="0.8" />`;
        svg += `<line x1="${px}" y1="${py + i * cellSz}" x2="${px + subGridMaxSize}" y2="${py + i * cellSz}" stroke="#E2E8F0" stroke-width="0.8" />`;
      }
    }

    puzzle.grid.forEach((gridRow, r) => {
      gridRow.forEach((cell, c) => {
        const cx = px + c * cellSz + cellSz / 2;
        const cy = py + r * cellSz + cellSz / 2;
        if (cell.isBlank) {
          svg += `<text x="${cx}" y="${cy + 5}" text-anchor="middle" font-family="Inter, sans-serif" font-size="${cellSz * 0.4}" fill="#CBD5E1">?</text>`;
          svg += `<rect x="${cx - cellSz * 0.38}" y="${cy - cellSz * 0.38}" width="${cellSz * 0.76}" height="${cellSz * 0.76}" rx="4" fill="none" stroke="#CBD5E1" stroke-width="1" stroke-dasharray="4,3" />`;
        } else {
          svg += getShapeSVG(cell.shape, cx, cy, cellSz * shapeScale, getFill(cell.shape), getStroke(cell.shape), getStrokeW(), cell.rotation);
        }
      });
    });
  });

  if (config.showAnswerKey) {
    const answers = puzzles.map((p, i) => `${i + 1}:${p.answer}`).join('  ');
    svg += `<text x="${W / 2}" y="${H - MARGIN - 28}" text-anchor="middle" font-family="Inter, sans-serif" font-size="9" fill="#94A3B8">Answers: ${answers}</text>`;
  }

  return svg;
}

// ========== MODE 3: MATCH PATTERN ==========
function renderPatternMode(
  config: WorksheetConfig,
  data: WorksheetData,
  shapeScale: number,
  getFill: (s: ShapeName) => string,
  getStroke: (s: ShapeName) => string,
  getStrokeW: () => number,
) {
  const puzzles = data.patternPuzzles!;
  let svg = '';

  const startY = MARGIN + 88;
  const availH = H - startY - MARGIN - 35;
  const rowH = availH / puzzles.length;
  const patternBoxSize = Math.min(rowH - 16, 90);
  const optionBoxSize = Math.min(patternBoxSize * 0.82, 68);

  const leftColX = MARGIN + 20;
  const rightColX = W / 2 + 10;
  const optionSpacing = (W - rightColX - MARGIN - 10) < optionBoxSize * 3.5
    ? optionBoxSize + 8
    : optionBoxSize + 16;

  puzzles.forEach((puzzle, pIdx) => {
    const rowY = startY + pIdx * rowH + (rowH - patternBoxSize) / 2;

    svg += `<text x="${leftColX - 12}" y="${rowY + patternBoxSize / 2 + 4}" text-anchor="middle" font-family="Nunito, sans-serif" font-size="13" font-weight="700" fill="#64748B">${pIdx + 1}.</text>`;
    svg += renderMiniGrid(puzzle.pattern, leftColX, rowY, patternBoxSize, shapeScale, getFill, getStroke, getStrokeW, config.showGridLines, config);

    const arrowX = leftColX + patternBoxSize + 14;
    const arrowY = rowY + patternBoxSize / 2;
    svg += `<line x1="${arrowX}" y1="${arrowY}" x2="${arrowX + 20}" y2="${arrowY}" stroke="#94A3B8" stroke-width="1.5" />`;
    svg += `<polygon points="${arrowX + 20},${arrowY - 4} ${arrowX + 28},${arrowY} ${arrowX + 20},${arrowY + 4}" fill="#94A3B8" />`;

    puzzle.options.forEach((option, oIdx) => {
      const ox = rightColX + oIdx * optionSpacing;
      const oy = rowY + (patternBoxSize - optionBoxSize) / 2;

      svg += `<text x="${ox + optionBoxSize / 2}" y="${oy - 4}" text-anchor="middle" font-family="Inter, sans-serif" font-size="9" font-weight="600" fill="#94A3B8">${String.fromCharCode(65 + oIdx)}</text>`;
      svg += renderMiniGrid(option, ox, oy, optionBoxSize, shapeScale * 0.85, getFill, getStroke, getStrokeW, false, config);
      svg += `<circle cx="${ox + optionBoxSize / 2}" cy="${oy + optionBoxSize + 8}" r="3" fill="none" stroke="#CBD5E1" stroke-width="1" />`;
    });

    svg += `<circle cx="${leftColX + patternBoxSize / 2}" cy="${rowY + patternBoxSize + 8}" r="3" fill="none" stroke="#CBD5E1" stroke-width="1" />`;
  });

  if (config.showAnswerKey) {
    const answers = puzzles.map((p, i) => `${i + 1}→${String.fromCharCode(65 + p.correctIndex)}`).join('  ');
    svg += `<text x="${W / 2}" y="${H - MARGIN - 28}" text-anchor="middle" font-family="Inter, sans-serif" font-size="9" fill="#94A3B8">Answers: ${answers}</text>`;
  }

  return svg;
}

function renderMiniGrid(
  grid: { shape: ShapeName; rotation?: number }[][],
  x: number,
  y: number,
  size: number,
  scale: number,
  getFill: (s: ShapeName) => string,
  getStroke: (s: ShapeName) => string,
  getStrokeW: () => number,
  showLines: boolean,
  config?: WorksheetConfig,
): string {
  const rows = grid.length;
  const cols = grid[0].length;
  const cellW = size / cols;
  const cellH = size / rows;
  let svg = '';

  if (config) {
    svg += `<rect x="${x}" y="${y}" width="${size}" height="${size}" ${getCellBorderAttrs(config, '#CBD5E1', 1.5)} />`;
  } else {
    svg += `<rect x="${x}" y="${y}" width="${size}" height="${size}" fill="none" stroke="#CBD5E1" stroke-width="1.5" rx="3" />`;
  }

  if (showLines) {
    for (let i = 1; i < cols; i++) {
      svg += `<line x1="${x + i * cellW}" y1="${y}" x2="${x + i * cellW}" y2="${y + size}" stroke="#E2E8F0" stroke-width="0.8" />`;
    }
    for (let i = 1; i < rows; i++) {
      svg += `<line x1="${x}" y1="${y + i * cellH}" x2="${x + size}" y2="${y + i * cellH}" stroke="#E2E8F0" stroke-width="0.8" />`;
    }
  }

  grid.forEach((row, r) => {
    row.forEach((cell, c) => {
      const cx = x + c * cellW + cellW / 2;
      const cy = y + r * cellH + cellH / 2;
      svg += getShapeSVG(cell.shape, cx, cy, Math.min(cellW, cellH) * scale, getFill(cell.shape), getStroke(cell.shape), getStrokeW(), cell.rotation);
    });
  });

  return svg;
}

// ========== MODE 4: FIND AND COUNT ==========
function renderCountMode(
  config: WorksheetConfig,
  data: WorksheetData,
  shapeScale: number,
  getFill: (s: ShapeName) => string,
  getStroke: (s: ShapeName) => string,
  getStrokeW: () => number,
) {
  const puzzle = data.countPuzzle!;
  const { grid, targetShapes } = puzzle;
  const ROWS = grid.length;
  const COLS = grid[0].length;

  let svg = '';

  const refY = MARGIN + 85;
  const refH = 62;
  const boxCount = targetShapes.length;
  const totalRefW = Math.min(boxCount * 100, W - MARGIN * 2);
  const refX = (W - totalRefW) / 2;
  const boxW = totalRefW / boxCount;

  targetShapes.forEach((shape, i) => {
    const bx = refX + i * boxW + 4;
    const bw = boxW - 8;
    svg += `<rect x="${bx}" y="${refY}" width="${bw}" height="${refH}" rx="6" fill="#F8FAFC" stroke="#CBD5E1" stroke-width="1.5" />`;
    svg += getShapeSVG(shape, bx + bw / 2, refY + 26, 36 * shapeScale, getFill(shape), getStroke(shape), getStrokeW());
    svg += `<line x1="${bx + bw * 0.25}" y1="${refY + refH - 10}" x2="${bx + bw * 0.75}" y2="${refY + refH - 10}" stroke="#94A3B8" stroke-width="1.5" />`;
  });

  const gridTop = refY + refH + 18;
  const gridAreaH = H - gridTop - MARGIN - 35;
  const gridAreaW = W - MARGIN * 2;
  const cellW = gridAreaW / COLS;
  const cellH = gridAreaH / ROWS;
  const cellSize = Math.min(cellW, cellH);
  const gridW = cellSize * COLS;
  const gridH = cellSize * ROWS;
  const gridX = (W - gridW) / 2;

  svg += `<rect x="${gridX}" y="${gridTop}" width="${gridW}" height="${gridH}" ${getBorderAttrs(config, '#CBD5E1', 2)} />`;

  if (config.showGridLines) {
    for (let c = 1; c < COLS; c++) {
      svg += `<line x1="${gridX + c * cellSize}" y1="${gridTop}" x2="${gridX + c * cellSize}" y2="${gridTop + gridH}" stroke="#E2E8F0" stroke-width="0.8" />`;
    }
    for (let r = 1; r < ROWS; r++) {
      svg += `<line x1="${gridX}" y1="${gridTop + r * cellSize}" x2="${gridX + gridW}" y2="${gridTop + r * cellSize}" stroke="#E2E8F0" stroke-width="0.8" />`;
    }
  }

  grid.forEach((row, r) => {
    row.forEach((cell, c) => {
      const cx = gridX + c * cellSize + cellSize / 2;
      const cy = gridTop + r * cellSize + cellSize / 2;
      svg += getShapeSVG(cell.shape, cx, cy, cellSize * shapeScale, getFill(cell.shape), getStroke(cell.shape), getStrokeW(), cell.rotation);
    });
  });

  if (config.showAnswerKey) {
    const answers = targetShapes.map(s => `${s}: ${puzzle.counts[s]}`).join('   ');
    svg += `<text x="${W / 2}" y="${gridTop + gridH + 16}" text-anchor="middle" font-family="Inter, sans-serif" font-size="9" fill="#94A3B8">Answers: ${answers}</text>`;
  }

  return svg;
}

// ========== MODE 5: COPY THE PATTERN ==========
function renderCopyMode(
  config: WorksheetConfig,
  data: WorksheetData,
  shapeScale: number,
  getFill: (s: ShapeName) => string,
  getStroke: (s: ShapeName) => string,
  getStrokeW: () => number,
) {
  const puzzles = data.copyPuzzles!;
  let svg = '';

  const startY = MARGIN + 88;
  const availH = H - startY - MARGIN - 35;
  const rowH = availH / puzzles.length;

  puzzles.forEach((puzzle, pIdx) => {
    const gridSize = puzzle.sourceGrid.length;
    const maxGridSz = Math.min(rowH - 20, 160);
    const cellSz = maxGridSz / gridSize;
    const gridSz = cellSz * gridSize;

    const rowY = startY + pIdx * rowH + (rowH - gridSz) / 2;
    const pairW = W - MARGIN * 2;
    const leftX = MARGIN + pairW * 0.05;
    const rightX = MARGIN + pairW * 0.55;

    svg += `<text x="${MARGIN}" y="${rowY + gridSz / 2 + 4}" font-family="Nunito, sans-serif" font-size="13" font-weight="700" fill="#64748B">${pIdx + 1}.</text>`;

    svg += `<rect x="${leftX}" y="${rowY}" width="${gridSz}" height="${gridSz}" ${getCellBorderAttrs(config, '#CBD5E1', 1.5)} />`;
    if (config.showGridLines) {
      for (let i = 1; i < gridSize; i++) {
        svg += `<line x1="${leftX + i * cellSz}" y1="${rowY}" x2="${leftX + i * cellSz}" y2="${rowY + gridSz}" stroke="#E2E8F0" stroke-width="0.8" />`;
        svg += `<line x1="${leftX}" y1="${rowY + i * cellSz}" x2="${leftX + gridSz}" y2="${rowY + i * cellSz}" stroke="#E2E8F0" stroke-width="0.8" />`;
      }
    }
    puzzle.sourceGrid.forEach((row, r) => {
      row.forEach((cell, c) => {
        const cx = leftX + c * cellSz + cellSz / 2;
        const cy = rowY + r * cellSz + cellSz / 2;
        svg += getShapeSVG(cell.shape, cx, cy, cellSz * shapeScale, getFill(cell.shape), getStroke(cell.shape), getStrokeW(), cell.rotation);
      });
    });

    const arrowX = leftX + gridSz + 8;
    const arrowY2 = rowY + gridSz / 2;
    svg += `<line x1="${arrowX}" y1="${arrowY2}" x2="${arrowX + 16}" y2="${arrowY2}" stroke="#94A3B8" stroke-width="1.5" />`;
    svg += `<polygon points="${arrowX + 16},${arrowY2 - 4} ${arrowX + 24},${arrowY2} ${arrowX + 16},${arrowY2 + 4}" fill="#94A3B8" />`;

    svg += `<rect x="${rightX}" y="${rowY}" width="${gridSz}" height="${gridSz}" ${getCellBorderAttrs(config, '#CBD5E1', 1.5)} />`;
    for (let i = 1; i < gridSize; i++) {
      svg += `<line x1="${rightX + i * cellSz}" y1="${rowY}" x2="${rightX + i * cellSz}" y2="${rowY + gridSz}" stroke="#E2E8F0" stroke-width="0.8" />`;
      svg += `<line x1="${rightX}" y1="${rowY + i * cellSz}" x2="${rightX + gridSz}" y2="${rowY + i * cellSz}" stroke="#E2E8F0" stroke-width="0.8" />`;
    }
  });

  return svg;
}

// ========== MODE 6: WHAT COMES NEXT ==========
function renderSequenceMode(
  config: WorksheetConfig,
  data: WorksheetData,
  shapeScale: number,
  getFill: (s: ShapeName) => string,
  getStroke: (s: ShapeName) => string,
  getStrokeW: () => number,
) {
  const puzzles = data.sequencePuzzles!;
  let svg = '';

  const startY = MARGIN + 88;
  const availH = H - startY - MARGIN - 35;
  const rowH = availH / puzzles.length;
  const cellSz = Math.min(rowH * 0.45, 50);

  puzzles.forEach((puzzle, pIdx) => {
    const rowY = startY + pIdx * rowH;
    const seqY = rowY + rowH * 0.18;

    svg += `<text x="${MARGIN + 4}" y="${seqY + cellSz / 2 + 4}" font-family="Nunito, sans-serif" font-size="12" font-weight="700" fill="#64748B">${pIdx + 1}.</text>`;

    const seqStartX = MARGIN + 28;
    for (let i = 0; i < 4; i++) {
      const cx = seqStartX + i * (cellSz + 8) + cellSz / 2;
      const cy = seqY + cellSz / 2;
      svg += `<rect x="${cx - cellSz / 2}" y="${cy - cellSz / 2}" width="${cellSz}" height="${cellSz}" ${getCellBorderAttrs(config, '#CBD5E1', 1)} />`;
      svg += getShapeSVG(puzzle.sequence[i].shape, cx, cy, cellSz * shapeScale, getFill(puzzle.sequence[i].shape), getStroke(puzzle.sequence[i].shape), getStrokeW(), puzzle.sequence[i].rotation);
    }

    const qx = seqStartX + 4 * (cellSz + 8) + cellSz / 2;
    const qy = seqY + cellSz / 2;
    svg += `<rect x="${qx - cellSz / 2}" y="${qy - cellSz / 2}" width="${cellSz}" height="${cellSz}" rx="4" fill="none" stroke="#CBD5E1" stroke-width="1.5" stroke-dasharray="6,4" />`;
    svg += `<text x="${qx}" y="${qy + 5}" text-anchor="middle" font-family="Nunito, sans-serif" font-size="${cellSz * 0.5}" font-weight="700" fill="#CBD5E1">?</text>`;

    const optStartX = seqStartX + 5 * (cellSz + 8) + 20;
    const optSize = cellSz * 0.85;
    puzzle.options.forEach((opt, oIdx) => {
      const ox = optStartX + oIdx * (optSize + 14) + optSize / 2;
      const oy = seqY + cellSz / 2;
      svg += `<text x="${ox}" y="${oy - optSize / 2 - 3}" text-anchor="middle" font-family="Inter, sans-serif" font-size="8" font-weight="600" fill="#94A3B8">${String.fromCharCode(65 + oIdx)}</text>`;
      svg += `<rect x="${ox - optSize / 2}" y="${oy - optSize / 2}" width="${optSize}" height="${optSize}" ${getCellBorderAttrs(config, '#94A3B8', 1)} />`;
      svg += getShapeSVG(opt.shape, ox, oy, optSize * shapeScale, getFill(opt.shape), getStroke(opt.shape), getStrokeW());
    });
  });

  if (config.showAnswerKey) {
    const answers = puzzles.map((p, i) => `${i + 1}→${String.fromCharCode(65 + p.correctIndex)}`).join('  ');
    svg += `<text x="${W / 2}" y="${H - MARGIN - 28}" text-anchor="middle" font-family="Inter, sans-serif" font-size="9" fill="#94A3B8">Answers: ${answers}</text>`;
  }

  return svg;
}

// ========== MODE 7: ODD ONE OUT ==========
function renderOddOneOutMode(
  config: WorksheetConfig,
  data: WorksheetData,
  shapeScale: number,
  getFill: (s: ShapeName) => string,
  getStroke: (s: ShapeName) => string,
  getStrokeW: () => number,
) {
  const rows = data.oddOneOutRows!;
  let svg = '';

  const startY = MARGIN + 88;
  const availH = H - startY - MARGIN - 35;
  const rowH = availH / rows.length;
  const cellSz = Math.min(rowH - 10, 60);
  const totalRowW = 5 * cellSz + 4 * 16;
  const rowStartX = (W - totalRowW) / 2;

  const isText = rows.length > 0 && rows[0].textItems && rows[0].textItems.length > 0;
  const fontSize = config.difficulty === 'easy' ? Math.min(cellSz * 0.7, 36) : config.difficulty === 'medium' ? Math.min(cellSz * 0.6, 28) : Math.min(cellSz * 0.5, 22);

  rows.forEach((row, rIdx) => {
    const rowY = startY + rIdx * rowH + (rowH - cellSz) / 2;

    svg += `<text x="${rowStartX - 18}" y="${rowY + cellSz / 2 + 4}" font-family="Nunito, sans-serif" font-size="12" font-weight="700" fill="#64748B">${rIdx + 1}.</text>`;

    if (isText && row.textItems) {
      row.textItems.forEach((char, i) => {
        const cx = rowStartX + i * (cellSz + 16) + cellSz / 2;
        const cy = rowY + cellSz / 2;
        svg += `<rect x="${cx - cellSz / 2}" y="${cy - cellSz / 2}" width="${cellSz}" height="${cellSz}" ${getCellBorderAttrs(config, '#CBD5E1', 1)} />`;
        svg += `<text x="${cx}" y="${cy + fontSize * 0.35}" text-anchor="middle" font-family="Inter, sans-serif" font-size="${fontSize}" font-weight="600" fill="#1E293B">${char}</text>`;
      });
    } else {
      row.items.forEach((cell, i) => {
        const cx = rowStartX + i * (cellSz + 16) + cellSz / 2;
        const cy = rowY + cellSz / 2;
        svg += `<rect x="${cx - cellSz / 2}" y="${cy - cellSz / 2}" width="${cellSz}" height="${cellSz}" ${getCellBorderAttrs(config, '#CBD5E1', 1)} />`;
        svg += getShapeSVG(cell.shape, cx, cy, cellSz * shapeScale, getFill(cell.shape), getStroke(cell.shape), getStrokeW(), cell.rotation);
      });
    }
  });

  if (config.showAnswerKey) {
    const answers = rows.map((r, i) => `${i + 1}:${r.oddIndex + 1}`).join('  ');
    svg += `<text x="${W / 2}" y="${H - MARGIN - 28}" text-anchor="middle" font-family="Inter, sans-serif" font-size="9" fill="#94A3B8">Answers (position): ${answers}</text>`;
  }

  return svg;
}

// ========== MODE 8: MIRROR IMAGE ==========
function renderMirrorMode(
  config: WorksheetConfig,
  data: WorksheetData,
  shapeScale: number,
  getFill: (s: ShapeName) => string,
  getStroke: (s: ShapeName) => string,
  getStrokeW: () => number,
) {
  const puzzles = data.mirrorPuzzles!;
  let svg = '';

  const startY = MARGIN + 88;
  const availH = H - startY - MARGIN - 35;
  const pairH = availH / puzzles.length;

  puzzles.forEach((puzzle, pIdx) => {
    const gridSize = puzzle.sourceGrid.length;
    const maxGridSz = Math.min(pairH - 30, 180, (W - MARGIN * 2 - 30) / 2);
    const cellSz = maxGridSz / gridSize;
    const gridSz = cellSz * gridSize;

    const pairY = startY + pIdx * pairH + (pairH - gridSz) / 2;
    const centerX = W / 2;
    const leftX = centerX - gridSz - 8;
    const rightX = centerX + 8;

    svg += `<text x="${W / 2}" y="${pairY - 8}" text-anchor="middle" font-family="Nunito, sans-serif" font-size="12" font-weight="700" fill="#64748B">${pIdx + 1}.</text>`;
    svg += `<line x1="${centerX}" y1="${pairY - 2}" x2="${centerX}" y2="${pairY + gridSz + 2}" stroke="#94A3B8" stroke-width="2" stroke-dasharray="8,5" />`;

    svg += `<rect x="${leftX}" y="${pairY}" width="${gridSz}" height="${gridSz}" ${getCellBorderAttrs(config, '#CBD5E1', 1.5)} />`;
    for (let i = 1; i < gridSize; i++) {
      svg += `<line x1="${leftX + i * cellSz}" y1="${pairY}" x2="${leftX + i * cellSz}" y2="${pairY + gridSz}" stroke="#E2E8F0" stroke-width="0.8" />`;
      svg += `<line x1="${leftX}" y1="${pairY + i * cellSz}" x2="${leftX + gridSz}" y2="${pairY + i * cellSz}" stroke="#E2E8F0" stroke-width="0.8" />`;
    }
    puzzle.sourceGrid.forEach((row, r) => {
      row.forEach((cell, c) => {
        if (cell) {
          const cx = leftX + c * cellSz + cellSz / 2;
          const cy = pairY + r * cellSz + cellSz / 2;
          svg += getShapeSVG(cell.shape, cx, cy, cellSz * shapeScale, getFill(cell.shape), getStroke(cell.shape), getStrokeW(), cell.rotation);
        }
      });
    });

    svg += `<rect x="${rightX}" y="${pairY}" width="${gridSz}" height="${gridSz}" ${getCellBorderAttrs(config, '#CBD5E1', 1.5)} />`;
    for (let i = 1; i < gridSize; i++) {
      svg += `<line x1="${rightX + i * cellSz}" y1="${pairY}" x2="${rightX + i * cellSz}" y2="${pairY + gridSz}" stroke="#E2E8F0" stroke-width="0.8" />`;
      svg += `<line x1="${rightX}" y1="${pairY + i * cellSz}" x2="${rightX + gridSz}" y2="${pairY + i * cellSz}" stroke="#E2E8F0" stroke-width="0.8" />`;
    }

    if (config.showAnswerKey) {
      puzzle.mirroredGrid.forEach((row, r) => {
        row.forEach((cell, c) => {
          if (cell) {
            const cx = rightX + c * cellSz + cellSz / 2;
            const cy = pairY + r * cellSz + cellSz / 2;
            svg += getShapeSVG(cell.shape, cx, cy, cellSz * shapeScale * 0.7, '#CBD5E1', '#94A3B8', 1, cell.rotation);
          }
        });
      });
    }
  });

  return svg;
}

// ========== MODE 9: FIGURE GROUND ==========
function renderFigureGroundMode(
  config: WorksheetConfig,
  data: WorksheetData,
  shapeScale: number,
  getFill: (s: ShapeName) => string,
  getStroke: (s: ShapeName) => string,
  getStrokeW: () => number,
) {
  const puzzle = data.figureGroundPuzzle!;
  const { shapes: placed, targetShapes } = puzzle;
  let svg = '';

  const refY = MARGIN + 85;
  const refH = 56;
  const boxCount = targetShapes.length;
  const totalRefW = Math.min(boxCount * 90, W - MARGIN * 2);
  const refX = (W - totalRefW) / 2;
  const boxW = totalRefW / boxCount;

  targetShapes.forEach((shape, i) => {
    const bx = refX + i * boxW + 4;
    const bw = boxW - 8;
    svg += `<rect x="${bx}" y="${refY}" width="${bw}" height="${refH}" rx="6" fill="#F8FAFC" stroke="#CBD5E1" stroke-width="1.5" />`;
    svg += getShapeSVG(shape, bx + bw / 2, refY + 24, 32, getFill(shape), getStroke(shape), getStrokeW());
    svg += `<line x1="${bx + bw * 0.25}" y1="${refY + refH - 10}" x2="${bx + bw * 0.75}" y2="${refY + refH - 10}" stroke="#94A3B8" stroke-width="1.5" />`;
  });

  const areaTop = refY + refH + 18;
  const areaH = H - areaTop - MARGIN - 35;
  const areaW = W - MARGIN * 2;
  const areaX = MARGIN;

  svg += `<rect x="${areaX}" y="${areaTop}" width="${areaW}" height="${areaH}" ${getBorderAttrs(config, '#CBD5E1', 1.5)} />`;

  const scaleX = areaW / 400;
  const scaleY = areaH / 400;

  placed.forEach(s => {
    const cx = areaX + s.cx * scaleX;
    const cy = areaTop + s.cy * scaleY;
    const r = s.r * Math.min(scaleX, scaleY);
    const raw = getShapeRawSVG(s.shape, cx, cy, r);
    const transform = s.rotation ? ` transform="rotate(${s.rotation}, ${cx}, ${cy})"` : '';
    svg += raw.replace('/>', ` fill="none" stroke="${getStroke(s.shape)}" stroke-width="2.5"${transform} />`);
  });

  if (config.showAnswerKey) {
    const answers = targetShapes.map(s => `${s}: ${puzzle.counts[s]}`).join('   ');
    svg += `<text x="${W / 2}" y="${areaTop + areaH + 14}" text-anchor="middle" font-family="Inter, sans-serif" font-size="9" fill="#94A3B8">Answers: ${answers}</text>`;
  }

  return svg;
}

// ========== MODE 10: VISUAL CLOSURE ==========
function renderClosureMode(
  config: WorksheetConfig,
  data: WorksheetData,
  shapeScale: number,
  getFill: (s: ShapeName) => string,
  getStroke: (s: ShapeName) => string,
  getStrokeW: () => number,
) {
  const puzzles = data.closurePuzzles!;
  let svg = '';

  const startY = MARGIN + 88;
  const availH = H - startY - MARGIN - 35;
  const cols = 2;
  const rows = Math.ceil(puzzles.length / cols);
  const cellW = (W - MARGIN * 2) / cols;
  const cellH = availH / rows;
  const shapeSz = Math.min(cellW * 0.4, cellH * 0.45, 70);

  puzzles.forEach((puzzle, idx) => {
    const col = idx % cols;
    const row = Math.floor(idx / cols);
    const cx = MARGIN + col * cellW + cellW / 2;
    const cy = startY + row * cellH + cellH * 0.32;

    svg += `<text x="${cx}" y="${cy - shapeSz / 2 - 10}" text-anchor="middle" font-family="Nunito, sans-serif" font-size="11" font-weight="700" fill="#64748B">${idx + 1}.</text>`;

    const raw = getShapeRawSVG(puzzle.shape, cx, cy, shapeSz);
    svg += raw.replace('/>', ` fill="none" stroke="${getStroke(puzzle.shape)}" stroke-width="3" stroke-dasharray="${puzzle.dashArray}" />`);

    const optY = cy + shapeSz / 2 + 20;
    const optSize = 24;
    const optSpacing = 42;
    const optStartX = cx - optSpacing;

    puzzle.options.forEach((opt, oIdx) => {
      const ox = optStartX + oIdx * optSpacing;
      svg += `<text x="${ox}" y="${optY - 6}" text-anchor="middle" font-family="Inter, sans-serif" font-size="8" font-weight="600" fill="#94A3B8">${String.fromCharCode(65 + oIdx)}</text>`;
      svg += getShapeSVG(opt, ox, optY + optSize / 2 + 2, optSize, getFill(opt), getStroke(opt), getStrokeW());
    });
  });

  if (config.showAnswerKey) {
    const answers = puzzles.map((p, i) => `${i + 1}→${String.fromCharCode(65 + p.correctIndex)}`).join('  ');
    svg += `<text x="${W / 2}" y="${H - MARGIN - 28}" text-anchor="middle" font-family="Inter, sans-serif" font-size="9" fill="#94A3B8">Answers: ${answers}</text>`;
  }

  return svg;
}

// ========== MODE 11: TRACE YOUR NAME ==========
function renderTraceNameMode(
  config: WorksheetConfig,
  data: WorksheetData,
) {
  const traceData = data.traceNameData!;
  if (!traceData || traceData.letters.length === 0) {
    return `<text x="${W / 2}" y="${H / 2}" text-anchor="middle" font-family="Nunito, sans-serif" font-size="16" fill="#94A3B8">Enter a name to generate tracing worksheet</text>`;
  }

  let svg = '';
  const letterH = config.difficulty === 'easy' ? 60 : config.difficulty === 'medium' ? 50 : 40;
  const letterW = letterH * 0.7;
  const startY = MARGIN + 90;
  const availH = H - startY - MARGIN - 35;

  // For each section of up to 5 letters
  const sectionCount = traceData.sections.length;
  const sectionH = availH / sectionCount;

  traceData.sections.forEach((section, sIdx) => {
    const secY = startY + sIdx * sectionH;
    const totalLetterW = section.length * (letterW + 12) - 12;
    const secStartX = (W - totalLetterW) / 2;

    // 3 rows: reference, dot-trace, blank
    const rowLabels = ['Reference', 'Trace', 'Write'];
    const rowH = Math.min(sectionH / 3 - 4, letterH + 20);

    for (let rowIdx = 0; rowIdx < 3; rowIdx++) {
      const rowY = secY + rowIdx * rowH;

      // Row label
      svg += `<text x="${MARGIN}" y="${rowY + rowH / 2 + 4}" font-family="Inter, sans-serif" font-size="8" fill="#94A3B8">${rowLabels[rowIdx]}</text>`;

      // Baseline
      svg += `<line x1="${secStartX - 5}" y1="${rowY + rowH - 4}" x2="${secStartX + totalLetterW + 5}" y2="${rowY + rowH - 4}" stroke="#E2E8F0" stroke-width="1" />`;
      // Midline (dashed)
      svg += `<line x1="${secStartX - 5}" y1="${rowY + rowH - 4 - letterH / 2}" x2="${secStartX + totalLetterW + 5}" y2="${rowY + rowH - 4 - letterH / 2}" stroke="#E2E8F0" stroke-width="0.5" stroke-dasharray="4,4" />`;
      // Topline
      svg += `<line x1="${secStartX - 5}" y1="${rowY + rowH - 4 - letterH}" x2="${secStartX + totalLetterW + 5}" y2="${rowY + rowH - 4 - letterH}" stroke="#E2E8F0" stroke-width="0.5" />`;

      section.forEach((letter, lIdx) => {
        const lx = secStartX + lIdx * (letterW + 12);
        const ly = rowY + rowH - 4 - letterH; // top of letter area
        const strokes = LETTER_PATHS[letter];
        if (!strokes) return;

        if (rowIdx === 0) {
          // Reference: solid light grey letter
          strokes.forEach(stroke => {
            if (stroke.length < 2) return;
            const points = stroke.map(([px, py]: StrokePoint) =>
              `${lx + px * letterW},${ly + py * letterH}`
            ).join(' ');
            svg += `<polyline points="${points}" fill="none" stroke="#CBD5E1" stroke-width="3" stroke-linecap="round" stroke-linejoin="round" />`;
          });
        } else if (rowIdx === 1) {
          // Dot-trace: dots along the stroke path
          strokes.forEach((stroke, strokeIdx) => {
            if (stroke.length < 2) return;
            // Draw dots along the path
            const dotSpacing = config.difficulty === 'easy' ? 6 : config.difficulty === 'medium' ? 8 : 10;
            const dotR = config.difficulty === 'easy' ? 2.5 : 2;

            // Interpolate points along each segment
            for (let si = 0; si < stroke.length - 1; si++) {
              const [x1, y1] = stroke[si];
              const [x2, y2] = stroke[si + 1];
              const segLen = Math.sqrt((x2 - x1) ** 2 + (y2 - y1) ** 2) * letterW;
              const dots = Math.max(2, Math.ceil(segLen / dotSpacing));

              for (let d = 0; d <= dots; d++) {
                const t = d / dots;
                const dx = lx + (x1 + (x2 - x1) * t) * letterW;
                const dy = ly + (y1 + (y2 - y1) * t) * letterH;
                svg += `<circle cx="${dx}" cy="${dy}" r="${dotR}" fill="#94A3B8" />`;
              }
            }

            // Starting dot (large green) for first stroke
            if (strokeIdx === 0) {
              const [sx, sy] = stroke[0];
              const startX = lx + sx * letterW;
              const startY2 = ly + sy * letterH;
              svg += `<circle cx="${startX}" cy="${startY2}" r="4.5" fill="#22C55E" />`;

              // Arrow showing direction
              if (stroke.length >= 2) {
                const [nx, ny] = stroke[1];
                const endX = lx + nx * letterW;
                const endY = ly + ny * letterH;
                const angle = Math.atan2(endY - startY2, endX - startX);
                const arrowLen = 10;
                const ax = startX + Math.cos(angle) * arrowLen;
                const ay = startY2 + Math.sin(angle) * arrowLen;
                svg += `<line x1="${startX}" y1="${startY2}" x2="${ax}" y2="${ay}" stroke="#22C55E" stroke-width="1.5" />`;
                svg += `<polygon points="${ax},${ay} ${ax - 4 * Math.cos(angle - 0.5)},${ay - 4 * Math.sin(angle - 0.5)} ${ax - 4 * Math.cos(angle + 0.5)},${ay - 4 * Math.sin(angle + 0.5)}" fill="#22C55E" />`;
              }
            }
          });
        }
        // rowIdx === 2: blank row, just the guidelines (already drawn above)
      });
    }
  });

  return svg;
}

// ========== MODE 12: HANDWRITING PRACTICE ==========

function isChinese(ch: string): boolean {
  const code = ch.charCodeAt(0);
  return code >= 0x4e00 && code <= 0x9fff;
}

function hasChinese(text: string): boolean {
  return Array.from(text).some(isChinese);
}

function isAllChinese(text: string): boolean {
  return Array.from(text).every(ch => isChinese(ch) || ch === ' ');
}

// Letter classification for adaptive box heights
const ASCENDERS = new Set('bdfhklt'.split(''));
const DESCENDERS = new Set('gjpqy'.split(''));
const CAPITALS = new Set('ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split(''));

function getLetterType(ch: string): 'tall' | 'medium' | 'descender' {
  if (CAPITALS.has(ch) || ASCENDERS.has(ch)) return 'tall';
  if (DESCENDERS.has(ch)) return 'descender';
  return 'medium';
}

// Line color hex mapping
const LINE_COLOR_MAP: Record<string, string> = {
  red: '#DC2626', blue: '#2563EB', green: '#16A34A', black: '#1E293B',
};

// Renders a 3-line set: colored top & bottom, grey/black dashed middle
function renderColoredTrilineSet(
  x: number, baselineY: number, fontPx: number, width: number, config: WorksheetConfig
): string {
  const lineMode = config.handwritingLineMode || '3-line';

  if (lineMode === '4-line') {
    return renderFourLineSet(x, baselineY, fontPx, width, config);
  }

  const zoneH = fontPx * 0.7;
  const topY = baselineY - zoneH;
  const midY = baselineY - zoneH / 2; // exact midpoint
  const botY = baselineY;

  const useColor = config.handwritingShowColoredLines;
  const lineColor = useColor ? (LINE_COLOR_MAP[config.handwritingLineColor] || '#DC2626') : '#94A3B8';

  let svg = '';
  // Top line (colored)
  svg += `<line x1="${x}" y1="${topY}" x2="${x + width}" y2="${topY}" stroke="${lineColor}" stroke-width="1.2" />`;
  // Middle dotted line (always grey)
  svg += `<line x1="${x}" y1="${midY}" x2="${x + width}" y2="${midY}" stroke="#94A3B8" stroke-width="0.8" stroke-dasharray="4 3" />`;
  // Bottom line (colored)
  svg += `<line x1="${x}" y1="${botY}" x2="${x + width}" y2="${botY}" stroke="${lineColor}" stroke-width="1.2" />`;

  return svg;
}

// 4-line HK copybook format: 4 evenly spaced solid lines (bottom, baseline, midline, top)
function renderFourLineSet(
  x: number, baselineY: number, fontPx: number, width: number, config: WorksheetConfig
): string {
  const zoneH = fontPx * 0.7;
  const topY = baselineY - zoneH;
  const botY = baselineY;
  const spacing = zoneH / 3; // 4 lines = 3 equal gaps

  const useColor = config.handwritingShowColoredLines;
  const lineColor = useColor ? (LINE_COLOR_MAP[config.handwritingLineColor] || '#DC2626') : '#94A3B8';

  let svg = '';
  for (let i = 0; i < 4; i++) {
    const ly = topY + i * spacing;
    svg += `<line x1="${x}" y1="${ly}" x2="${x + width}" y2="${ly}" stroke="${lineColor}" stroke-width="1.2" />`;
  }
  return svg;
}

// Add a trace overlay (rendered as HTML div, not SVG)
function addTraceOverlay(text: string, x: number, baselineY: number, fontPx: number, contentW: number) {
  const topY = baselineY - fontPx * 0.85; // approximate ascender offset
  _traceOverlays.push({
    text,
    x,
    y: topY,
    fontPx,
    width: contentW,
  });
}

// Render text on tri-lines — text y = baselineY exactly
function renderTextOnTriline(
  chars: string[], x: number, baselineY: number, fontPx: number, contentW: number,
  fontFamily: string, color: string, isDottedTrace: boolean, showStartEnd: boolean = false
): string {
  if (chars.length === 0) return '';
  const charW = Math.min(fontPx * 0.62, contentW / Math.max(chars.length, 1));
  let svg = '';

  if (isDottedTrace) {
    // Use dotted font rendered as HTML overlay
    addTraceOverlay(chars.join(''), x + 4, baselineY, fontPx, contentW);
  } else {
    for (let c = 0; c < chars.length; c++) {
      const cx = x + 4 + c * charW + charW / 2;
      if (cx > x + contentW) break;
      svg += `<text x="${cx}" y="${baselineY}" text-anchor="middle" font-family="${fontFamily}" font-size="${fontPx}" font-weight="500" fill="${color}">${escapeXml(chars[c])}</text>`;
    }
  }

  // Start/end dots per letter
  if (showStartEnd && isDottedTrace) {
    for (let c = 0; c < chars.length; c++) {
      const cx = x + 4 + c * charW + charW / 2;
      if (cx > x + contentW) break;
      const dotR = Math.max(2.5, fontPx * 0.06);
      svg += `<circle cx="${cx - charW * 0.3}" cy="${baselineY - fontPx * 0.55}" r="${dotR}" fill="#22C55E" />`;
      svg += `<circle cx="${cx + charW * 0.3}" cy="${baselineY}" r="${dotR}" fill="#EF4444" />`;
    }
  }

  return svg;
}

// Sentence mode: 3-row groups (reference / trace / blank) with colored tri-lines
// lineH here = the raw mm-based size used as fontPx for the trace text
function renderSentenceTrilineMode(
  text: string, rows: number, startY: number, availableH: number,
  lineH: number, contentW: number, fontFamily: string, config: WorksheetConfig
): string {
  const mmToPx = 2.833;
  const fontPx = lineH; // lineH in px IS the font size
  const zoneH = fontPx * 0.7; // top-to-bottom line distance
  const grassH = zoneH * 0.15;
  const triSetH = zoneH + grassH; // total visual height of one tri-line set
  const groupGap = 12 * mmToPx;
  const setGap = 6 * mmToPx;
  const refFontPx = fontPx * 0.55;
  const refTextH = Math.max(fontPx * 0.85, 10 * mmToPx + refFontPx); // min 10mm gap between ref text bottom and top line
  const groupH = refTextH + triSetH + setGap + triSetH + groupGap;
  const maxGroups = Math.min(rows, Math.floor(availableH / groupH));
  const allChars = Array.from(text);
  // Auto-calculate trace font size so ascenders fill the zone
  const traceFontPx = zoneH / 0.72;
  let svg = '';

  for (let g = 0; g < maxGroups; g++) {
    const groupY = startY + g * groupH;

    // Row 1: Reference text as dotted trace using KG Primary Dots font overlay
    const refBaselineY = groupY + refTextH * 0.85;
    addTraceOverlay(allChars.join(''), MARGIN + 4, refBaselineY, refFontPx, contentW);

    // Row 2: Dotted trace on colored tri-lines
    // baseline = botY of the tri-line set; topY = baselineY - zoneH
    const traceBaselineY = groupY + refTextH + zoneH;
    svg += renderColoredTrilineSet(MARGIN, traceBaselineY, fontPx, contentW, config);
    svg += renderTextOnTriline(allChars, MARGIN, traceBaselineY, traceFontPx, contentW, fontFamily, '#94A3B8', true, config.handwritingShowStartEnd);

    // Row 3: Blank colored tri-lines for independent writing
    const blankBaselineY = traceBaselineY + grassH + setGap + zoneH;
    svg += renderColoredTrilineSet(MARGIN, blankBaselineY, fontPx, contentW, config);
  }

  return svg;
}

function renderGridBoxRows(
  chars: string[], rows: number, startY: number, availableH: number,
  boxSize: number, gapBetweenSets: number, contentW: number,
  fontFamily: string, isDotted: boolean, ghostColor: string, config: WorksheetConfig,
  sectionLabel?: string
): { svg: string; usedH: number } {
  const rowH = boxSize + gapBetweenSets * 0.5;
  const maxRows = Math.min(rows, Math.floor(availableH / rowH));
  const maxCols = Math.floor(contentW / boxSize);
  const charCount = Math.min(chars.length, maxCols);
  let svg = '';

  if (sectionLabel) {
    svg += `<text x="${MARGIN}" y="${startY - 4}" font-family="Nunito, sans-serif" font-size="11" font-weight="700" fill="#64748B">${escapeXml(sectionLabel)}</text>`;
  }

  for (let r = 0; r < maxRows; r++) {
    const baseY = startY + r * rowH;
    for (let c = 0; c < charCount; c++) {
      const bx = MARGIN + c * boxSize;
      const borderAttrs = getCellBorderAttrs(config, '#94A3B8', 1);
      svg += `<rect x="${bx}" y="${baseY}" width="${boxSize}" height="${boxSize}" ${borderAttrs} />`;

      if (r === 0) {
        const ch = chars[c];
        const charFontPx = boxSize * 0.65;
        if (isDotted) {
          addTraceOverlay(ch, bx + boxSize * 0.15, baseY + boxSize * 0.72, charFontPx, boxSize * 0.7);
        } else {
          svg += `<text x="${bx + boxSize / 2}" y="${baseY + boxSize * 0.72}" text-anchor="middle" font-family="${fontFamily}" font-size="${charFontPx}" font-weight="400" fill="${ghostColor}">${escapeXml(ch)}</text>`;
        }
      }
    }
  }
  return { svg, usedH: maxRows * rowH };
}

// ========== WORD BOXES SUB-MODE ==========
function renderWordBoxesMode(config: WorksheetConfig, data: WorksheetData): string {
  if (!data.handwritingData) return '';
  const { words, fontSizeMm, font } = data.handwritingData;
  if (words.length === 0) return '';

  const mmToPx = 2.833;
  const fontFamilyMap: Record<string, string> = {
    print: "Arial, Helvetica, sans-serif",
    cursive: "'Segoe Script', 'Comic Sans MS', cursive",
  };
  const fontFamily = fontFamilyMap[font] || fontFamilyMap.print;

  const contentW = W - MARGIN * 2;
  const startY = MARGIN + 90;
  const availableH = H - startY - MARGIN - 30;
  const colW = (contentW - 20) / 2; // 2 columns with 20px gap
  const lineH = fontSizeMm * mmToPx;

  // Sizing
  const tallH = Math.max(25 * mmToPx, lineH);
  const medH = Math.max(18 * mmToPx, lineH * 0.72);
  const descH = tallH;
  const descExtra = 7 * mmToPx;
  const labelH = 16;
  const trilineSetH = lineH;
  const gapBetweenParts = 6 * mmToPx;

  const displayMode = config.wordBoxDisplayMode || 'boxOnly';
  const showTriline = displayMode === 'trilineOnly' || displayMode === 'both';
  const showBoxes = displayMode === 'boxOnly' || displayMode === 'both';

  const wordBlockH = labelH + (showTriline ? trilineSetH + gapBetweenParts : 0) + (showBoxes ? tallH + descExtra + gapBetweenParts : 0) + gapBetweenParts;
  const maxPerCol = Math.min(4, Math.floor(availableH / wordBlockH));

  let svg = '';

  words.slice(0, maxPerCol * 2).forEach((word, wIdx) => {
    const col = wIdx % 2;
    const row = Math.floor(wIdx / 2);
    if (row >= maxPerCol) return;

    const colX = MARGIN + col * (colW + 20);
    const blockY = startY + row * wordBlockH;
    const chars = Array.from(word.trim());
    if (chars.length === 0) return;

    // 1. Word label as dotted trace using font overlay
    addTraceOverlay(word.trim(), colX, blockY + 12, 13, colW);

    let nextY = blockY + labelH;

    // 2. Tri-line trace (if enabled)
    if (showTriline) {
      const fontPxTrace = lineH;
      const zoneH = fontPxTrace * 0.7;
      const grassH = zoneH * 0.15;
      const traceFontPx = zoneH / 0.72;
      const traceBaselineY = nextY + zoneH;
      svg += renderColoredTrilineSet(colX, traceBaselineY, fontPxTrace, colW, config);
      svg += renderTextOnTriline(chars, colX, traceBaselineY, traceFontPx, colW, fontFamily, '#94A3B8', true, config.handwritingShowStartEnd);
      nextY = traceBaselineY + grassH + gapBetweenParts;
    }

    // 3. Adaptive word boxes (if enabled)
    if (showBoxes) {
      const boxesY = nextY;
      const boxW = Math.min(colW / chars.length, tallH * 0.8);
      const baseline = boxesY + tallH;

      chars.forEach((ch, cIdx) => {
        const bx = colX + cIdx * boxW;
        const type = getLetterType(ch);
        let boxTop: number;
        let boxHeight: number;

        if (type === 'tall') {
          boxTop = boxesY;
          boxHeight = tallH;
        } else if (type === 'descender') {
          boxTop = baseline - medH;
          boxHeight = medH + descExtra;
        } else {
          boxTop = baseline - medH;
          boxHeight = medH;
        }

        svg += `<rect x="${bx}" y="${boxTop}" width="${boxW}" height="${boxHeight}" fill="none" stroke="#1E293B" stroke-width="1.8" rx="2" />`;

        if (cIdx === 0) {
          svg += `<line x1="${colX}" y1="${baseline}" x2="${colX + chars.length * boxW}" y2="${baseline}" stroke="#DC2626" stroke-width="0.6" stroke-dasharray="3 2" />`;
        }
      });
    }
  });

  return svg;
}

function renderHandwritingMode(config: WorksheetConfig, data: WorksheetData): string {
  if (!data.handwritingData) return '';
  const { text, rows, paperStyle, fontSizeMm, font, subMode } = data.handwritingData;

  // Word Boxes sub-mode
  if (subMode === 'wordBoxes') {
    return renderWordBoxesMode(config, data);
  }

  const mmToPx = 2.833;
  const lineH = fontSizeMm * mmToPx;
  const boxSize = fontSizeMm * mmToPx;
  const gapBetweenSets = 8 * mmToPx;
  const contentW = W - MARGIN * 2;
  const startY = MARGIN + 90;
  const availableH = H - startY - MARGIN - 30;

  const fontFamilyMap: Record<string, string> = {
    print: "Arial, Helvetica, sans-serif",
    cursive: "'Segoe Script', 'Comic Sans MS', cursive",
  };
  const fontFamily = fontFamilyMap[font] || fontFamilyMap.print;
  const ghostColor = '#C8CDD3';
  const isDotted = false;
  const allChars = Array.from(text);

  let svg = '';

  const containsChinese = hasChinese(text);
  const allChinese = isAllChinese(text);

  // Determine rendering strategy based on content + paper style
  if (paperStyle === 'gridbox') {
    const result = renderGridBoxRows(allChars, rows, startY, availableH, boxSize, gapBetweenSets, contentW, fontFamily, isDotted, ghostColor, config);
    svg += result.svg;
  } else if (paperStyle === 'both') {
    if (allChinese) {
      const result = renderGridBoxRows(allChars, rows, startY, availableH, boxSize, gapBetweenSets, contentW, fontFamily, isDotted, ghostColor, config, 'Grid Box Paper (方格紙)');
      svg += result.svg;
    } else if (containsChinese) {
      const engChars = allChars.filter(ch => !isChinese(ch));
      const chnChars = allChars.filter(isChinese);
      const halfH = availableH * 0.48;
      // English tri-line (colored) at top
      svg += renderSentenceTrilineMode(engChars.join(''), Math.max(1, Math.floor(rows / 2)), startY, halfH, lineH, contentW, fontFamily, config);
      const gridStartY = startY + availableH * 0.52;
      const gridResult = renderGridBoxRows(chnChars, Math.max(1, Math.ceil(rows / 2)), gridStartY, halfH, boxSize, gapBetweenSets, contentW, fontFamily, isDotted, ghostColor, config, 'Grid Box Paper (方格紙)');
      svg += gridResult.svg;
    } else {
      const halfH = availableH * 0.48;
      svg += renderSentenceTrilineMode(text, Math.max(1, Math.floor(rows / 2)), startY, halfH, lineH, contentW, fontFamily, config);
      const gridStartY = startY + availableH * 0.52;
      const gridResult = renderGridBoxRows(allChars, Math.max(1, Math.ceil(rows / 2)), gridStartY, halfH, boxSize, gapBetweenSets, contentW, fontFamily, isDotted, ghostColor, config, 'Grid Box Paper (方格紙)');
      svg += gridResult.svg;
    }
  } else {
    // Tri-line mode — now uses colored HWT-style lines with sentence groups
    if (allChinese) {
      // Chinese: first row grid boxes, remaining blank colored tri-lines
      const rowH = boxSize + gapBetweenSets * 0.5;
      const maxCols = Math.floor(contentW / boxSize);
      const charCount = Math.min(allChars.length, maxCols);

      for (let c = 0; c < charCount; c++) {
        const bx = MARGIN + c * boxSize;
        const borderAttrs = getCellBorderAttrs(config, '#94A3B8', 1);
        svg += `<rect x="${bx}" y="${startY}" width="${boxSize}" height="${boxSize}" ${borderAttrs} />`;
        const ch = allChars[c];
        const charFontPx = boxSize * 0.65;
        svg += `<text x="${bx + boxSize / 2}" y="${startY + boxSize * 0.72}" text-anchor="middle" font-family="${fontFamily}" font-size="${charFontPx}" font-weight="400" fill="${ghostColor}">${escapeXml(ch)}</text>`;
      }

      // Blank colored tri-lines below
      const triStartY = startY + rowH;
      const remainH = availableH - rowH;
      const fontPxBlank = lineH;
      const zoneHBlank = fontPxBlank * 0.7;
      const grassHBlank = zoneHBlank * 0.15;
      const triSetHBlank = zoneHBlank + grassHBlank;
      const setGap = 4 * mmToPx;
      const setH = triSetHBlank + setGap;
      const blankRows = Math.min(rows - 1, Math.floor(remainH / setH));
      for (let r = 0; r < blankRows; r++) {
        const blankBaselineY = triStartY + r * setH + zoneHBlank;
        svg += renderColoredTrilineSet(MARGIN, blankBaselineY, fontPxBlank, contentW, config);
      }
    } else if (containsChinese) {
      const engChars = allChars.filter(ch => !isChinese(ch));
      const chnChars = allChars.filter(isChinese);
      const rowH = boxSize + gapBetweenSets * 0.5;
      const maxCols = Math.floor(contentW / boxSize);
      const charCount = Math.min(chnChars.length, maxCols);

      svg += `<text x="${MARGIN}" y="${startY - 4}" font-family="Nunito, sans-serif" font-size="11" font-weight="700" fill="#64748B">Chinese — Grid Box (方格紙)</text>`;
      for (let c = 0; c < charCount; c++) {
        const bx = MARGIN + c * boxSize;
        const borderAttrs = getCellBorderAttrs(config, '#94A3B8', 1);
        svg += `<rect x="${bx}" y="${startY}" width="${boxSize}" height="${boxSize}" ${borderAttrs} />`;
        const charFontPx = boxSize * 0.65;
        svg += `<text x="${bx + boxSize / 2}" y="${startY + boxSize * 0.72}" text-anchor="middle" font-family="${fontFamily}" font-size="${charFontPx}" font-weight="400" fill="${ghostColor}">${escapeXml(chnChars[c])}</text>`;
      }

      const triStartY = startY + rowH + gapBetweenSets * 0.5;
      const remainH = availableH - rowH - gapBetweenSets * 0.5;
      svg += renderSentenceTrilineMode(engChars.join(''), Math.max(1, rows - 1), triStartY, remainH, lineH, contentW, fontFamily, config);
    } else {
      // Pure English: colored tri-line with 3-row sentence groups
      svg += renderSentenceTrilineMode(text, rows, startY, availableH, lineH, contentW, fontFamily, config);
    }
  }

  return svg;
}

// ========== MODE 13: MAZE ==========
function renderMazeMode(config: WorksheetConfig, data: WorksheetData): string {
  const maze = data.mazeData!;
  const { grid, rows, cols, shape, solution } = maze;

  const startY = MARGIN + 88;
  const availH = H - startY - MARGIN - 45;
  const availW = W - MARGIN * 2;
  const cellSize = Math.min(availW / cols, availH / rows);
  const mazeW = cellSize * cols;
  const mazeH = cellSize * rows;
  const mazeX = (W - mazeW) / 2;
  const mazeY = startY + (availH - mazeH) / 2;

  let svg = '';

  // Circle clip mask
  if (shape === 'circle') {
    const clipCx = mazeX + mazeW / 2;
    const clipCy = mazeY + mazeH / 2;
    const clipR = Math.min(mazeW, mazeH) / 2;
    svg += `<defs><clipPath id="maze-circle"><circle cx="${clipCx}" cy="${clipCy}" r="${clipR}" /></clipPath></defs>`;
    svg += `<circle cx="${clipCx}" cy="${clipCy}" r="${clipR}" fill="none" stroke="#1E293B" stroke-width="2.5" />`;
    svg += `<g clip-path="url(#maze-circle)">`;
  }

  // Draw walls
  for (let r = 0; r < rows; r++) {
    for (let c = 0; c < cols; c++) {
      const x = mazeX + c * cellSize;
      const y = mazeY + r * cellSize;
      const cell = grid[r][c];
      const sw = 1.5;
      const color = '#1E293B';
      if (cell.top) svg += `<line x1="${x}" y1="${y}" x2="${x + cellSize}" y2="${y}" stroke="${color}" stroke-width="${sw}" stroke-linecap="round" />`;
      if (cell.right) svg += `<line x1="${x + cellSize}" y1="${y}" x2="${x + cellSize}" y2="${y + cellSize}" stroke="${color}" stroke-width="${sw}" stroke-linecap="round" />`;
      if (cell.bottom) svg += `<line x1="${x}" y1="${y + cellSize}" x2="${x + cellSize}" y2="${y + cellSize}" stroke="${color}" stroke-width="${sw}" stroke-linecap="round" />`;
      if (cell.left) svg += `<line x1="${x}" y1="${y}" x2="${x}" y2="${y + cellSize}" stroke="${color}" stroke-width="${sw}" stroke-linecap="round" />`;
    }
  }

  if (shape === 'circle') {
    svg += `</g>`;
  }

  // Solution path
  if (config.difficulty === 'easy' && config.mazeShowSolution && solution.length > 1) {
    const pathD = solution.map((p, i) => {
      const px = mazeX + p[1] * cellSize + cellSize / 2;
      const py = mazeY + p[0] * cellSize + cellSize / 2;
      return `${i === 0 ? 'M' : 'L'} ${px} ${py}`;
    }).join(' ');
    svg += `<path d="${pathD}" fill="none" stroke="#94A3B8" stroke-width="1.5" stroke-dasharray="4,3" opacity="0.5" />`;
  }

  // Start marker (green circle)
  const startCx = mazeX + cellSize / 2;
  const startCy = mazeY + cellSize / 2;
  svg += `<circle cx="${startCx}" cy="${startCy}" r="${cellSize * 0.25}" fill="#22C55E" />`;
  svg += `<text x="${startCx}" y="${startCy + 3}" text-anchor="middle" font-family="Inter, sans-serif" font-size="${cellSize * 0.22}" font-weight="700" fill="white">S</text>`;

  // End marker (red star)
  const endCx = mazeX + (cols - 0.5) * cellSize;
  const endCy = mazeY + (rows - 0.5) * cellSize;
  const starR = cellSize * 0.25;
  const starPts: string[] = [];
  for (let i = 0; i < 5; i++) {
    const aOuter = -Math.PI / 2 + (2 * Math.PI * i) / 5;
    const aInner = aOuter + Math.PI / 5;
    starPts.push(`${endCx + Math.cos(aOuter) * starR},${endCy + Math.sin(aOuter) * starR}`);
    starPts.push(`${endCx + Math.cos(aInner) * starR * 0.4},${endCy + Math.sin(aInner) * starR * 0.4}`);
  }
  svg += `<polygon points="${starPts.join(' ')}" fill="#EF4444" />`;

  return svg;
}

// ========== MODE 14: CONNECT THE DOTS ==========
function renderConnectDotsMode(config: WorksheetConfig, data: WorksheetData): string {
  const dots = data.connectDotsData!;
  const { dots: dotList, completedPath, shapeName } = dots;

  const startY = MARGIN + 88;
  const availH = H - startY - MARGIN - 45;
  const availW = W - MARGIN * 2;
  // Leave bottom quarter for coloring
  const drawH = availH * 0.75;
  const drawSize = Math.min(availW, drawH);
  const scale = drawSize / 400;
  const offsetX = (W - drawSize) / 2;
  const offsetY = startY + 10;

  let svg = '';

  // Small reference image in top-right corner (20% size)
  const refSize = drawSize * 0.18;
  const refScale = refSize / 400;
  const refX = W - MARGIN - refSize - 5;
  const refY = startY + 5;
  svg += `<rect x="${refX - 3}" y="${refY - 3}" width="${refSize + 6}" height="${refSize + 6}" rx="4" fill="#F8FAFC" stroke="#E2E8F0" stroke-width="1" />`;
  svg += `<text x="${refX + refSize / 2}" y="${refY - 7}" text-anchor="middle" font-family="Inter, sans-serif" font-size="7" fill="#94A3B8">Preview</text>`;
  const refPath = dotList.map((d, i) => `${i === 0 ? 'M' : 'L'} ${refX + d.x * refScale} ${refY + d.y * refScale}`).join(' ') + ' Z';
  svg += `<path d="${refPath}" fill="none" stroke="#CBD5E1" stroke-width="1" />`;

  // Draw dots
  const dotRadius = Math.max(3, 5 - dotList.length * 0.03);
  const fontSize = Math.max(6, 9 - dotList.length * 0.05);

  dotList.forEach((dot) => {
    const x = offsetX + dot.x * scale;
    const y = offsetY + dot.y * scale;
    svg += `<circle cx="${x}" cy="${y}" r="${dotRadius}" fill="#1E293B" />`;

    // Number label - offset to avoid overlap
    const angle = Math.atan2(dot.y - 200, dot.x - 200);
    const labelDist = dotRadius + fontSize * 0.8;
    const lx = x + Math.cos(angle) * labelDist;
    const ly = y + Math.sin(angle) * labelDist + fontSize * 0.35;
    svg += `<text x="${lx}" y="${ly}" text-anchor="middle" font-family="Inter, sans-serif" font-size="${fontSize}" font-weight="600" fill="#64748B">${dot.index}</text>`;
  });

  // Coloring area label
  const colorY = offsetY + drawSize + 15;
  svg += `<text x="${W / 2}" y="${colorY}" text-anchor="middle" font-family="Nunito, sans-serif" font-size="11" font-weight="600" fill="#94A3B8">✏️ Colour your picture here!</text>`;
  svg += `<rect x="${offsetX}" y="${colorY + 8}" width="${drawSize}" height="${availH * 0.2}" rx="6" fill="none" stroke="#E2E8F0" stroke-width="1" stroke-dasharray="6,4" />`;

  return svg;
}

// ========== MODE 15: TRACING PATHS ==========
function renderTracingPathsMode(config: WorksheetConfig, data: WorksheetData): string {
  const paths = data.tracingPathsData!;
  const startY = MARGIN + 88;
  const availH = H - startY - MARGIN - 45;
  const availW = W - MARGIN * 2;
  const rowCount = paths.rows.length;
  const rowH = availH / rowCount;
  const scaleX = availW / 460;

  const thickness = config.tracingThickness === 'thick' ? 4 : config.tracingThickness === 'thin' ? 1.5 : 2.5;
  const dashArray = config.tracingThickness === 'thick' ? '10 6' : config.tracingThickness === 'thin' ? '4 3' : '6 4';

  let svg = '';

  paths.rows.forEach((row, i) => {
    const offsetY = startY + i * rowH;
    // Scale the path
    const pathD = row.pathD.replace(/(\d+\.?\d*)\s+(\d+\.?\d*)/g, (_, x, y) => {
      return `${MARGIN + parseFloat(x) * scaleX} ${offsetY + parseFloat(y) * (rowH / (availH / rowCount))}`;
    });

    // Actually, let's compute more carefully
    const baseRowH = availH / rowCount; // expected unscaled row height
    const totalUnscaledH = paths.rows.length > 0 ? (() => {
      // Rows are generated with varying rowH based on difficulty
      const isEasy = config.difficulty === 'easy';
      const isMedium = config.difficulty === 'medium';
      return isEasy ? 100 : isMedium ? 80 : 60;
    })() : 80;
    const scaleY2 = rowH / totalUnscaledH;

    // Re-render path with proper transforms
    const sX = MARGIN + row.startX * scaleX;
    const sY = offsetY + (row.startY - i * totalUnscaledH) * scaleY2;
    const eX = MARGIN + row.endX * scaleX;
    const eY = offsetY + (row.endY - i * totalUnscaledH) * scaleY2;

    // Transform path coordinates
    const transformedPath = row.pathD.replace(/([ML])\s*([\d.]+)\s+([\d.]+)/g, (_, cmd, x, y) => {
      const tx = MARGIN + parseFloat(x) * scaleX;
      const ty = offsetY + (parseFloat(y) - i * totalUnscaledH) * scaleY2;
      return `${cmd} ${tx} ${ty}`;
    }).replace(/([CQ])\s*([\d.]+)\s+([\d.]+)\s+([\d.]+)\s+([\d.]+)\s+([\d.]+)\s+([\d.]+)/g, (_, cmd, x1, y1, x2, y2, x3, y3) => {
      const tx1 = MARGIN + parseFloat(x1) * scaleX;
      const ty1 = offsetY + (parseFloat(y1) - i * totalUnscaledH) * scaleY2;
      const tx2 = MARGIN + parseFloat(x2) * scaleX;
      const ty2 = offsetY + (parseFloat(y2) - i * totalUnscaledH) * scaleY2;
      const tx3 = MARGIN + parseFloat(x3) * scaleX;
      const ty3 = offsetY + (parseFloat(y3) - i * totalUnscaledH) * scaleY2;
      return `${cmd} ${tx1} ${ty1} ${tx2} ${ty2} ${tx3} ${ty3}`;
    }).replace(/([Q])\s*([\d.]+)\s+([\d.]+)\s+([\d.]+)\s+([\d.]+)/g, (_, cmd, x1, y1, x2, y2) => {
      const tx1 = MARGIN + parseFloat(x1) * scaleX;
      const ty1 = offsetY + (parseFloat(y1) - i * totalUnscaledH) * scaleY2;
      const tx2 = MARGIN + parseFloat(x2) * scaleX;
      const ty2 = offsetY + (parseFloat(y2) - i * totalUnscaledH) * scaleY2;
      return `${cmd} ${tx1} ${ty1} ${tx2} ${ty2}`;
    });

    // Dotted guide path
    svg += `<path d="${transformedPath}" fill="none" stroke="#94A3B8" stroke-width="${thickness}" stroke-dasharray="${dashArray}" stroke-linecap="round" />`;

    // Start (green) and end (red) markers
    svg += `<circle cx="${sX}" cy="${sY}" r="${thickness + 3}" fill="#22C55E" />`;
    svg += `<circle cx="${eX}" cy="${eY}" r="${thickness + 2}" fill="#EF4444" />`;

    // Direction arrow near start
    const arrowAngle = Math.atan2(eY - sY, eX - sX);
    const arrowLen = 12;
    const ax = sX + Math.cos(arrowAngle) * arrowLen;
    const ay = sY + Math.sin(arrowAngle) * arrowLen;
    svg += `<line x1="${sX}" y1="${sY}" x2="${ax}" y2="${ay}" stroke="#22C55E" stroke-width="2" />`;
    svg += `<polygon points="${ax},${ay} ${ax - 5 * Math.cos(arrowAngle - 0.5)},${ay - 5 * Math.sin(arrowAngle - 0.5)} ${ax - 5 * Math.cos(arrowAngle + 0.5)},${ay - 5 * Math.sin(arrowAngle + 0.5)}" fill="#22C55E" />`;

    // Row label
    svg += `<text x="${MARGIN - 5}" y="${sY + 4}" text-anchor="end" font-family="Nunito, sans-serif" font-size="10" font-weight="700" fill="#94A3B8">${i + 1}</text>`;
  });

  return svg;
}

// ========== MODE 16: SCISSOR SKILLS ==========
function renderScissorSkillsMode(config: WorksheetConfig, data: WorksheetData): string {
  const scissors = data.scissorSkillsData!;
  const startY = MARGIN + 88;
  const availH = H - startY - MARGIN - 45;
  const availW = W - MARGIN * 2;
  const lineCount = scissors.lines.length;
  const lineSpacing = availH / lineCount;
  const scaleX = availW / 460;

  let svg = '';

  scissors.lines.forEach((line, i) => {
    const y = startY + i * lineSpacing + lineSpacing / 2;

    // Transform path
    const transformedPath = line.pathD.replace(/([ML])\s*([\d.]+)\s+([\d.-]+)/g, (_, cmd, x, yVal) => {
      return `${cmd} ${MARGIN + parseFloat(x) * scaleX} ${y + parseFloat(yVal)}`;
    }).replace(/([C])\s*([\d.]+)\s+([\d.-]+)\s+([\d.]+)\s+([\d.-]+)\s+([\d.]+)\s+([\d.-]+)/g, (_, cmd, x1, y1, x2, y2, x3, y3) => {
      return `${cmd} ${MARGIN + parseFloat(x1) * scaleX} ${y + parseFloat(y1)} ${MARGIN + parseFloat(x2) * scaleX} ${y + parseFloat(y2)} ${MARGIN + parseFloat(x3) * scaleX} ${y + parseFloat(y3)}`;
    });

    // Dashed cutting line
    svg += `<path d="${transformedPath}" fill="none" stroke="#1E293B" stroke-width="2.5" stroke-dasharray="8 4" stroke-linecap="round" />`;

    // Scissors icon at start
    const scissorX = MARGIN + line.startX * scaleX - 18;
    const scissorY = y;
    svg += `<text x="${scissorX}" y="${scissorY + 5}" font-family="sans-serif" font-size="16" fill="#64748B">✂</text>`;

    // Small arrow showing cut direction
    const arrowX = MARGIN + line.startX * scaleX + 5;
    svg += `<polygon points="${arrowX},${y - 3} ${arrowX + 8},${y} ${arrowX},${y + 3}" fill="#94A3B8" />`;
  });

  return svg;
}

// ========== MODE 17: COLOR BY NUMBER ==========
function renderColorByNumberMode(config: WorksheetConfig, data: WorksheetData): string {
  const cbn = data.colorByNumberData!;
  const startY = MARGIN + 88;
  const availH = H - startY - MARGIN - 45;
  const availW = W - MARGIN * 2;

  let svg = '';

  // Color key at top
  const keyH = 40;
  const keyItemW = availW / cbn.colorKey.length;
  cbn.colorKey.forEach((ck, i) => {
    const kx = MARGIN + i * keyItemW + keyItemW / 2;
    const ky = startY + keyH / 2;
    // Color swatch
    const swatchFill = config.colorByNumberBW ? 'none' : ck.color;
    const swatchStroke = config.colorByNumberBW ? '#1E293B' : ck.color;
    svg += `<rect x="${kx - 28}" y="${ky - 10}" width="20" height="20" rx="3" fill="${swatchFill}" stroke="${swatchStroke}" stroke-width="1.5" />`;
    svg += `<text x="${kx - 18}" y="${ky + 5}" text-anchor="middle" font-family="Nunito, sans-serif" font-size="11" font-weight="700" fill="${config.colorByNumberBW ? '#1E293B' : 'white'}">${ck.index}</text>`;
    svg += `<text x="${kx + 5}" y="${ky + 4}" font-family="Inter, sans-serif" font-size="9" fill="#64748B">${ck.name}</text>`;
  });

  // Draw regions
  const drawTop = startY + keyH + 15;
  const drawH = availH - keyH - 15;
  const scaleX = availW / 460;
  const scaleY = drawH / 420;

  cbn.regions.forEach(region => {
    // Transform path
    const transformedPath = region.pathD.replace(/([\d.]+)\s+([\d.]+)/g, (_, x, y) => {
      return `${MARGIN + parseFloat(x) * scaleX} ${drawTop + parseFloat(y) * scaleY}`;
    });

    const fill = config.colorByNumberBW ? 'none' : 'none'; // Always outline for coloring
    svg += `<path d="${transformedPath}" fill="${fill}" stroke="#1E293B" stroke-width="1.5" />`;

    // Number label
    const lx = MARGIN + region.labelX * scaleX;
    const ly = drawTop + region.labelY * scaleY;
    svg += `<text x="${lx}" y="${ly}" text-anchor="middle" font-family="Nunito, sans-serif" font-size="14" font-weight="700" fill="#64748B">${region.colorIndex}</text>`;
  });

  return svg;
}

// ========== MODE 18: GRID DESIGNS ==========
function renderGridDesignsMode(config: WorksheetConfig, data: WorksheetData): string {
  const gd = data.gridDesignData!;
  const startY = MARGIN + 88;
  const availH = H - startY - MARGIN - 45;
  const availW = W - MARGIN * 2;
  const gridSize = gd.gridSize;

  // Two grids side by side
  const gap = 30;
  const maxGridW = (availW - gap) / 2;
  const maxGridH = availH - 30;
  const cellSize = Math.min(maxGridW / gridSize, maxGridH / gridSize);
  const gridW = cellSize * gridSize;
  const gridH = cellSize * gridSize;
  const leftX = (W / 2 - gap / 2) - gridW;
  const rightX = W / 2 + gap / 2;
  const gridY = startY + (availH - gridH) / 2;

  let svg = '';

  // Labels
  svg += `<text x="${leftX + gridW / 2}" y="${gridY - 10}" text-anchor="middle" font-family="Nunito, sans-serif" font-size="11" font-weight="700" fill="#64748B">Copy this pattern →</text>`;
  svg += `<text x="${rightX + gridW / 2}" y="${gridY - 10}" text-anchor="middle" font-family="Nunito, sans-serif" font-size="11" font-weight="700" fill="#94A3B8">Your turn</text>`;

  // Draw both grids
  [leftX, rightX].forEach((gx, gridIdx) => {
    // Thick outer border
    svg += `<rect x="${gx}" y="${gridY}" width="${gridW}" height="${gridH}" fill="none" stroke="#1E293B" stroke-width="2.5" rx="2" />`;

    // Thin inner grid lines
    for (let i = 1; i < gridSize; i++) {
      svg += `<line x1="${gx + i * cellSize}" y1="${gridY}" x2="${gx + i * cellSize}" y2="${gridY + gridH}" stroke="#CBD5E1" stroke-width="1" />`;
      svg += `<line x1="${gx}" y1="${gridY + i * cellSize}" x2="${gx + gridW}" y2="${gridY + i * cellSize}" stroke="#CBD5E1" stroke-width="1" />`;
    }

    // Fill left grid only
    if (gridIdx === 0) {
      gd.grid.forEach((row, r) => {
        row.forEach((cell, c) => {
          const cx = gx + c * cellSize + cellSize / 2;
          const cy = gridY + r * cellSize + cellSize / 2;
          const sz = cellSize * 0.5;

          if (cell.type === 'shape') {
            switch (cell.value) {
              case 'circle':
                svg += `<circle cx="${cx}" cy="${cy}" r="${sz * 0.4}" fill="#3B82F6" stroke="#1E293B" stroke-width="1" />`;
                break;
              case 'square':
                svg += `<rect x="${cx - sz * 0.35}" y="${cy - sz * 0.35}" width="${sz * 0.7}" height="${sz * 0.7}" fill="#EF4444" stroke="#1E293B" stroke-width="1" />`;
                break;
              case 'triangle': {
                const h = sz * 0.4;
                svg += `<polygon points="${cx},${cy - h} ${cx - h},${cy + h * 0.7} ${cx + h},${cy + h * 0.7}" fill="#22C55E" stroke="#1E293B" stroke-width="1" />`;
                break;
              }
              case 'cross':
                svg += `<line x1="${cx - sz * 0.3}" y1="${cy - sz * 0.3}" x2="${cx + sz * 0.3}" y2="${cy + sz * 0.3}" stroke="#F59E0B" stroke-width="2.5" stroke-linecap="round" />`;
                svg += `<line x1="${cx + sz * 0.3}" y1="${cy - sz * 0.3}" x2="${cx - sz * 0.3}" y2="${cy + sz * 0.3}" stroke="#F59E0B" stroke-width="2.5" stroke-linecap="round" />`;
                break;
              case 'dot':
                svg += `<circle cx="${cx}" cy="${cy}" r="${sz * 0.15}" fill="#1E293B" />`;
                break;
            }
          } else if (cell.type === 'color') {
            svg += `<rect x="${gx + c * cellSize + 1}" y="${gridY + r * cellSize + 1}" width="${cellSize - 2}" height="${cellSize - 2}" fill="${cell.color}" />`;
          } else if (cell.type === 'line') {
            switch (cell.value) {
              case 'diagonal-lr':
                svg += `<line x1="${cx - sz * 0.35}" y1="${cy - sz * 0.35}" x2="${cx + sz * 0.35}" y2="${cy + sz * 0.35}" stroke="#1E293B" stroke-width="2" stroke-linecap="round" />`;
                break;
              case 'diagonal-rl':
                svg += `<line x1="${cx + sz * 0.35}" y1="${cy - sz * 0.35}" x2="${cx - sz * 0.35}" y2="${cy + sz * 0.35}" stroke="#1E293B" stroke-width="2" stroke-linecap="round" />`;
                break;
              case 'cross':
                svg += `<line x1="${cx - sz * 0.3}" y1="${cy}" x2="${cx + sz * 0.3}" y2="${cy}" stroke="#1E293B" stroke-width="2" stroke-linecap="round" />`;
                svg += `<line x1="${cx}" y1="${cy - sz * 0.3}" x2="${cx}" y2="${cy + sz * 0.3}" stroke="#1E293B" stroke-width="2" stroke-linecap="round" />`;
                break;
              case 'dot':
                svg += `<circle cx="${cx}" cy="${cy}" r="${sz * 0.12}" fill="#1E293B" />`;
                break;
            }
          }
        });
      });
    }
  });

  // Arrow between grids
  const arrowY = gridY + gridH / 2;
  const arrowX1 = leftX + gridW + 5;
  const arrowX2 = rightX - 5;
  svg += `<line x1="${arrowX1}" y1="${arrowY}" x2="${arrowX2}" y2="${arrowY}" stroke="#94A3B8" stroke-width="1.5" />`;
  svg += `<polygon points="${arrowX2},${arrowY - 4} ${arrowX2 + 6},${arrowY} ${arrowX2},${arrowY + 4}" fill="#94A3B8" />`;

  return svg;
}

function escapeXml(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&apos;');
}

// ========== MODE 19: DOT ART ==========
function renderDotArtMode(config: WorksheetConfig, data: WorksheetData): string {
  const da = data.dotArtData!;
  const startY = MARGIN + 88;
  const availH = H - startY - MARGIN - 45;
  const availW = W - MARGIN * 2;
  const dotSizeMm = config.dotArtDotSize === 'large' ? 25 : config.dotArtDotSize === 'medium' ? 18 : 12;
  const dotR = dotSizeMm * 2.833 / 2;

  // Scale dots to fit area
  const scaleX = availW / 400;
  const scaleY = availH / 500;

  let svg = '';

  // Reference image (15% size) in top right
  const refScale = 0.12;
  const refW = availW * refScale;
  const refH = availH * refScale;
  const refX = W - MARGIN - refW - 5;
  const refY = startY + 5;
  svg += `<rect x="${refX - 3}" y="${refY - 3}" width="${refW + 6}" height="${refH + 6}" fill="none" stroke="#CBD5E1" stroke-width="1" rx="3" />`;
  svg += `<text x="${refX + refW / 2}" y="${refY + refH + 12}" text-anchor="middle" font-family="Inter, sans-serif" font-size="7" fill="#94A3B8">Reference</text>`;

  // Draw reference dots (filled)
  da.dots.forEach(dot => {
    const rx = refX + dot.x * refScale * scaleX;
    const ry = refY + dot.y * refScale * scaleY;
    const color = config.dotArtColorMode === 'colored' ? da.regionColors[dot.region % da.regionColors.length] : '#64748B';
    svg += `<circle cx="${rx}" cy="${ry}" r="${dotR * refScale}" fill="${color}" />`;
  });

  // Draw main dots (stroke only)
  da.dots.forEach(dot => {
    const dx = MARGIN + dot.x * scaleX;
    const dy = startY + 20 + dot.y * scaleY;
    const strokeColor = config.dotArtColorMode === 'colored' ? da.regionColors[dot.region % da.regionColors.length] : '#94A3B8';
    svg += `<circle cx="${dx}" cy="${dy}" r="${dotR}" fill="none" stroke="${strokeColor}" stroke-width="1.5" />`;
  });

  return svg;
}

// ========== MODE 20: SHAPE TRACING ==========
function renderShapeTracingMode(config: WorksheetConfig, data: WorksheetData): string {
  const st = data.shapeTracingData!;
  const startY = MARGIN + 88;
  const availH = H - startY - MARGIN - 45;
  const availW = W - MARGIN * 2;
  const rowCount = st.shapes.length;
  const rowH = availH / rowCount;

  let svg = '';

  st.shapes.forEach((shape, i) => {
    const cy = startY + i * rowH + rowH / 2;
    const cx = MARGIN + availW / 2;
    const scale = Math.min(availW / 600, rowH / 200) * (config.shapeTracingSize === 'large' ? 1.2 : config.shapeTracingSize === 'small' ? 0.7 : 1.0);

    // Row separator
    if (i > 0) {
      svg += `<line x1="${MARGIN}" y1="${startY + i * rowH}" x2="${W - MARGIN}" y2="${startY + i * rowH}" stroke="#E2E8F0" stroke-width="0.5" stroke-dasharray="4 4" />`;
    }

    // Shape label
    svg += `<text x="${MARGIN + 5}" y="${startY + i * rowH + 14}" font-family="Inter, sans-serif" font-size="9" fill="#94A3B8">${shape.shapeName}</text>`;

    // Transform path to center in row
    const transformedPath = shape.pathD
      .replace(/([\d.-]+)\s*,\s*([\d.-]+)/g, (_, x, y) => {
        const tx = cx + (parseFloat(x) - 250) * scale;
        const ty = cy + parseFloat(y) * scale;
        return `${tx},${ty}`;
      })
      .replace(/([MLAQCZ])\s*([\d.-]+)\s+([\d.-]+)/g, (_, cmd, x, y) => {
        if (cmd === 'Z') return cmd;
        const tx = cx + (parseFloat(x) - 250) * scale;
        const ty = cy + parseFloat(y) * scale;
        return `${cmd} ${tx} ${ty}`;
      });

    // Dotted outline (guide)
    const dashGap = config.difficulty === 'easy' ? '8 6' : config.difficulty === 'hard' ? '4 3' : '6 5';
    svg += `<path d="${transformedPath}" fill="none" stroke="#CBD5E1" stroke-width="2.5" stroke-dasharray="${dashGap}" stroke-linecap="round" />`;

    // Starting dot
    if (config.shapeTracingShowStart) {
      const sx = cx + (shape.startX - 250) * scale;
      const sy = cy + shape.startY * scale;
      svg += `<circle cx="${sx}" cy="${sy}" r="5" fill="#22C55E" />`;

      // Direction arrow
      const arrowLen = 15;
      const ax = sx + Math.cos(shape.arrowAngle) * arrowLen;
      const ay = sy + Math.sin(shape.arrowAngle) * arrowLen;
      svg += `<line x1="${sx}" y1="${sy}" x2="${ax}" y2="${ay}" stroke="#22C55E" stroke-width="2" />`;
      svg += `<polygon points="${ax},${ay} ${ax - 4 * Math.cos(shape.arrowAngle - 0.5)},${ay - 4 * Math.sin(shape.arrowAngle - 0.5)} ${ax - 4 * Math.cos(shape.arrowAngle + 0.5)},${ay - 4 * Math.sin(shape.arrowAngle + 0.5)}" fill="#22C55E" />`;
    }

    // Second row: blank outline for independent tracing
    if (rowCount <= 4 && i < rowCount) {
      // Leave space — the blank is implicit (dotted lines above are the guide)
    }
  });

  return svg;
}

// ========== MODE 21: SPOT THE DIFFERENCE ==========
function renderSpotDifferenceMode(config: WorksheetConfig, data: WorksheetData): string {
  const sd = data.spotDiffData!;
  const startY = MARGIN + 88;
  const availH = H - startY - MARGIN - 65;
  const availW = W - MARGIN * 2;

  const gap = 15;
  const sceneW = (availW - gap) / 2;
  const sceneH = availH - 40;
  const scaleX = sceneW / 400;
  const scaleY = sceneH / 400;

  let svg = '';

  // Labels
  svg += `<text x="${MARGIN + sceneW / 2}" y="${startY - 3}" text-anchor="middle" font-family="Nunito, sans-serif" font-size="10" font-weight="700" fill="#64748B">Picture A</text>`;
  svg += `<text x="${MARGIN + sceneW + gap + sceneW / 2}" y="${startY - 3}" text-anchor="middle" font-family="Nunito, sans-serif" font-size="10" font-weight="700" fill="#94A3B8">Picture B</text>`;

  function renderScene(scene: typeof sd.leftScene, offsetX: number) {
    let s = '';
    s += `<rect x="${offsetX}" y="${startY}" width="${sceneW}" height="${sceneH}" fill="none" stroke="#CBD5E1" stroke-width="1.5" rx="4" />`;
    s += `<clipPath id="clip-${offsetX}"><rect x="${offsetX}" y="${startY}" width="${sceneW}" height="${sceneH}" /></clipPath>`;
    s += `<g clip-path="url(#clip-${offsetX})">`;

    scene.forEach(obj => {
      if (obj.extra?.hidden) return;
      const ox = offsetX + obj.x * scaleX;
      const oy = startY + obj.y * scaleY;
      const ow = obj.w * scaleX;
      const oh = obj.h * scaleY;

      switch (obj.type) {
        case 'rect':
          s += `<rect x="${ox}" y="${oy}" width="${ow}" height="${oh}" fill="${obj.fill}" />`;
          break;
        case 'circle':
          s += `<circle cx="${ox + ow / 2}" cy="${oy + oh / 2}" r="${Math.min(ow, oh) / 2}" fill="${obj.fill}" />`;
          break;
        case 'ellipse':
          s += `<ellipse cx="${ox + ow / 2}" cy="${oy + oh / 2}" rx="${ow / 2}" ry="${oh / 2}" fill="${obj.fill}" />`;
          break;
        case 'triangle':
          s += `<polygon points="${ox + ow / 2},${oy} ${ox + ow},${oy + oh} ${ox},${oy + oh}" fill="${obj.fill}" />`;
          break;
      }
    });

    s += '</g>';
    return s;
  }

  svg += renderScene(sd.leftScene, MARGIN);
  svg += renderScene(sd.rightScene, MARGIN + sceneW + gap);

  // Answer key circles
  if (config.spotDiffShowAnswers) {
    sd.differences.forEach(diff => {
      // Mark on right scene
      const dx = MARGIN + sceneW + gap + diff.x * scaleX;
      const dy = startY + diff.y * scaleY;
      svg += `<circle cx="${dx}" cy="${dy}" r="${diff.r * Math.min(scaleX, scaleY)}" fill="none" stroke="#EF4444" stroke-width="2" stroke-dasharray="4 3" />`;
    });
  }

  // Counter circles at bottom
  const counterY = startY + sceneH + 15;
  for (let i = 0; i < sd.differences.length; i++) {
    const cx = MARGIN + availW / 2 - (sd.differences.length * 20) / 2 + i * 20 + 10;
    svg += `<circle cx="${cx}" cy="${counterY}" r="7" fill="none" stroke="#94A3B8" stroke-width="1.5" />`;
    svg += `<text x="${cx}" y="${counterY + 3.5}" text-anchor="middle" font-family="Inter, sans-serif" font-size="8" fill="#CBD5E1">${i + 1}</text>`;
  }

  return svg;
}

// ========== MODE 22: VISUAL SCANNING ==========
function renderVisualScanningMode(config: WorksheetConfig, data: WorksheetData): string {
  const vs = data.visualScanData!;
  const startY = MARGIN + 88;
  const availH = H - startY - MARGIN - 45;
  const availW = W - MARGIN * 2;
  const charSize = config.visualScanCharSize === 'large' ? 18 : config.visualScanCharSize === 'small' ? 12 : 15;

  const cellW = availW / vs.cols;
  const cellH = availH / vs.rows;

  let svg = '';

  // Grid
  for (let r = 0; r < vs.rows; r++) {
    for (let c = 0; c < vs.cols; c++) {
      const x = MARGIN + c * cellW;
      const y = startY + r * cellH;

      // Cell border
      svg += `<rect x="${x}" y="${y}" width="${cellW}" height="${cellH}" fill="none" stroke="#E2E8F0" stroke-width="0.5" />`;

      // Character
      const ch = vs.grid[r][c];
      const isTarget = ch === vs.target;
      const isHighlighted = config.showAnswerKey && isTarget;

      if (isHighlighted) {
        svg += `<rect x="${x + 1}" y="${y + 1}" width="${cellW - 2}" height="${cellH - 2}" fill="#DCFCE7" rx="3" />`;
      }

      const fontFamily = config.visualScanFontStyle === 'dyslexia' ? 'OpenDyslexic, sans-serif' : 'Inter, sans-serif';
      svg += `<text x="${x + cellW / 2}" y="${y + cellH / 2 + charSize * 0.35}" text-anchor="middle" font-family="${fontFamily}" font-size="${charSize}" font-weight="500" fill="#1E293B">${escapeXml(ch)}</text>`;
    }
  }

  // Target count at bottom
  svg += `<text x="${W / 2}" y="${startY + availH + 15}" text-anchor="middle" font-family="Inter, sans-serif" font-size="10" fill="#94A3B8">Total '${escapeXml(vs.target)}' to find: ${vs.targetPositions.length}</text>`;

  return svg;
}

// ========== MODE 23: PIXEL ART ==========
function renderPixelArtMode(config: WorksheetConfig, data: WorksheetData): string {
  const pa = data.pixelArtData!;
  const startY = MARGIN + 88;
  const availH = H - startY - MARGIN - 45;
  const availW = W - MARGIN * 2;
  const gridSize = pa.gridSize;

  // Color key at top
  const keyH = 35;
  const keyItemW = availW / pa.colorKey.length;
  let svg = '';

  pa.colorKey.forEach((ck, i) => {
    const kx = MARGIN + i * keyItemW + keyItemW / 2;
    const ky = startY + keyH / 2;
    const swatchFill = config.pixelArtBW ? 'none' : ck.color;
    const swatchStroke = config.pixelArtBW ? '#1E293B' : ck.color;
    svg += `<rect x="${kx - 25}" y="${ky - 10}" width="18" height="18" rx="2" fill="${swatchFill}" stroke="${swatchStroke}" stroke-width="1.5" />`;
    svg += `<text x="${kx - 16}" y="${ky + 4}" text-anchor="middle" font-family="Nunito, sans-serif" font-size="10" font-weight="700" fill="${config.pixelArtBW ? '#1E293B' : (ck.index === 0 ? '#64748B' : 'white')}">${ck.index}</text>`;
    svg += `<text x="${kx + 2}" y="${ky + 3}" font-family="Inter, sans-serif" font-size="8" fill="#64748B">${ck.name}</text>`;
  });

  // Grid
  const drawTop = startY + keyH + 10;
  const drawH = availH - keyH - 15;
  const cellSize = Math.min(drawH / gridSize, availW / (pa.grid[0]?.length || gridSize));
  const gridW = cellSize * (pa.grid[0]?.length || gridSize);
  const gridH = cellSize * gridSize;
  const gridX = MARGIN + (availW - gridW) / 2;

  for (let r = 0; r < gridSize; r++) {
    for (let c = 0; c < (pa.grid[r]?.length || gridSize); c++) {
      const x = gridX + c * cellSize;
      const y = drawTop + r * cellSize;
      const colorIdx = pa.grid[r]?.[c] || 0;

      svg += `<rect x="${x}" y="${y}" width="${cellSize}" height="${cellSize}" fill="none" stroke="#CBD5E1" stroke-width="0.5" />`;

      // Number in cell
      const fontSize = Math.min(cellSize * 0.45, 14);
      svg += `<text x="${x + cellSize / 2}" y="${y + cellSize / 2 + fontSize * 0.35}" text-anchor="middle" font-family="Inter, sans-serif" font-size="${fontSize}" font-weight="600" fill="#64748B">${colorIdx}</text>`;
    }
  }

  // Outer border
  svg += `<rect x="${gridX}" y="${drawTop}" width="${gridW}" height="${gridH}" fill="none" stroke="#1E293B" stroke-width="2" rx="2" />`;

  return svg;
}
