import { WorksheetConfig, WorksheetData, ShapeName, SHAPE_COLORS, getShapeSVG, getShapeRawSVG } from '@/lib/shapes';

interface Props {
  config: WorksheetConfig;
  data: WorksheetData;
}

const W = 595;
const H = 842;
const MARGIN = 40;
const BW_FILL = 'none';
const BW_STROKE = '#1E293B';

export default function WorksheetPreview({ config, data }: Props) {
  const getFill = (shape: ShapeName) => config.useColor ? SHAPE_COLORS[shape] : BW_FILL;
  const getStroke = (shape: ShapeName) => config.useColor ? SHAPE_COLORS[shape] : BW_STROKE;
  const getStrokeW = () => config.useColor ? 1.5 : 2.5;

  const shapeScale = config.difficulty === 'easy' ? 1.15 : config.difficulty === 'medium' ? 1.0 : 0.85;

  // Common header
  const headerSVG = `
    <text x="${W / 2}" y="${MARGIN + 22}" text-anchor="middle" font-family="Nunito, sans-serif" font-size="20" font-weight="800" fill="#0D9488">OTsheet.ai</text>
    <line x1="${MARGIN}" y1="${MARGIN + 32}" x2="${W - MARGIN}" y2="${MARGIN + 32}" stroke="#E2E8F0" stroke-width="1" />
    <text x="${MARGIN}" y="${MARGIN + 52}" font-family="Nunito, sans-serif" font-size="12" font-weight="600" fill="#334155">Name: ${config.childName || '___________________'}</text>
    <text x="${W - MARGIN}" y="${MARGIN + 52}" text-anchor="end" font-family="Inter, sans-serif" font-size="11" fill="#94A3B8">Date: ____/____/________</text>
    <text x="${W / 2}" y="${MARGIN + 72}" text-anchor="middle" font-family="Nunito, sans-serif" font-size="14" font-weight="700" fill="#1E293B">${data.instructions}</text>
  `;

  // Footer with skill label
  const footerSVG = `
    <line x1="${MARGIN}" y1="${H - MARGIN - 20}" x2="${W - MARGIN}" y2="${H - MARGIN - 20}" stroke="#E2E8F0" stroke-width="1" />
    <text x="${MARGIN}" y="${H - MARGIN - 4}" font-family="Inter, sans-serif" font-size="10" font-weight="600" fill="#94A3B8">Skill: ${data.skillLabel}</text>
    <text x="${W - MARGIN}" y="${H - MARGIN - 4}" text-anchor="end" font-family="Inter, sans-serif" font-size="9" fill="#CBD5E1">Generated by OTsheet.ai</text>
  `;

  let bodySVG = '';

  if (data.mode === 'find') {
    bodySVG = renderFindMode(config, data, shapeScale, getFill, getStroke, getStrokeW);
  } else if (data.mode === 'missing') {
    bodySVG = renderMissingMode(config, data, shapeScale, getFill, getStroke, getStrokeW);
  } else if (data.mode === 'pattern') {
    bodySVG = renderPatternMode(config, data, shapeScale, getFill, getStroke, getStrokeW);
  } else if (data.mode === 'count') {
    bodySVG = renderCountMode(config, data, shapeScale, getFill, getStroke, getStrokeW);
  }

  const svgContent = `
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H}" width="100%" height="100%">
      <rect width="${W}" height="${H}" fill="white" rx="4" />
      ${headerSVG}
      ${bodySVG}
      ${footerSVG}
    </svg>
  `;

  return (
    <div
      id="worksheet-preview"
      className="bg-card rounded-xl shadow-lg border border-border overflow-hidden"
      style={{ aspectRatio: '210/297', maxHeight: '85vh' }}
      dangerouslySetInnerHTML={{ __html: svgContent }}
    />
  );
}

// ========== MODE 1: FIND THE SHAPE ==========
function renderFindMode(
  config: WorksheetConfig,
  data: WorksheetData,
  shapeScale: number,
  getFill: (s: ShapeName) => string,
  getStroke: (s: ShapeName) => string,
  getStrokeW: () => number,
) {
  const targetShape = data.targetShape!;
  const grid = data.grid!;
  const size = config.gridSize;

  // Reference box
  const refBoxY = MARGIN + 85;
  const refBoxH = 64;
  const refBoxW = 200;
  const refBoxX = (W - refBoxW) / 2;

  let svg = '';
  // Dashed reference box
  svg += `<rect x="${refBoxX}" y="${refBoxY}" width="${refBoxW}" height="${refBoxH}" rx="8" fill="none" stroke="#94A3B8" stroke-width="2" stroke-dasharray="8,5" />`;
  svg += `<text x="${refBoxX + 12}" y="${refBoxY + 16}" font-family="Inter, sans-serif" font-size="10" fill="#64748B">Find this shape:</text>`;
  svg += getShapeSVG(targetShape, refBoxX + refBoxW / 2, refBoxY + refBoxH / 2 + 5, 50 * shapeScale, getFill(targetShape), getStroke(targetShape), getStrokeW());

  // Main grid
  const gridTop = refBoxY + refBoxH + 20;
  const gridAreaH = H - gridTop - MARGIN - 35;
  const gridAreaW = W - MARGIN * 2;
  const cellSize = Math.min(gridAreaW / size, gridAreaH / size);
  const gridW = cellSize * size;
  const gridH = cellSize * size;
  const gridX = (W - gridW) / 2;

  svg += `<rect x="${gridX}" y="${gridTop}" width="${gridW}" height="${gridH}" fill="none" stroke="#CBD5E1" stroke-width="2" rx="4" />`;

  if (config.showGridLines) {
    for (let i = 1; i < size; i++) {
      svg += `<line x1="${gridX + i * cellSize}" y1="${gridTop}" x2="${gridX + i * cellSize}" y2="${gridTop + gridH}" stroke="#E2E8F0" stroke-width="1" />`;
      svg += `<line x1="${gridX}" y1="${gridTop + i * cellSize}" x2="${gridX + gridW}" y2="${gridTop + i * cellSize}" stroke="#E2E8F0" stroke-width="1" />`;
    }
  }

  grid.forEach((row, r) => {
    row.forEach((cell, c) => {
      const cx = gridX + c * cellSize + cellSize / 2;
      const cy = gridTop + r * cellSize + cellSize / 2;
      svg += getShapeSVG(cell.shape, cx, cy, cellSize * shapeScale, getFill(cell.shape), getStroke(cell.shape), getStrokeW(), cell.rotation);
    });
  });

  // Answer key
  if (config.showAnswerKey) {
    let count = 0;
    grid.forEach(row => row.forEach(cell => { if (cell.isTarget) count++; }));
    svg += `<text x="${W / 2}" y="${gridTop + gridH + 18}" text-anchor="middle" font-family="Inter, sans-serif" font-size="10" fill="#94A3B8">Answer: ${count} ${targetShape}${count !== 1 ? 's' : ''}</text>`;
  }

  return svg;
}

// ========== MODE 2: MISSING SHAPE ==========
function renderMissingMode(
  config: WorksheetConfig,
  data: WorksheetData,
  shapeScale: number,
  getFill: (s: ShapeName) => string,
  getStroke: (s: ShapeName) => string,
  getStrokeW: () => number,
) {
  const refShapes = data.referenceShapes!;
  const puzzles = data.missingPuzzles!;

  let svg = '';

  // Reference bar showing all shapes
  const refY = MARGIN + 85;
  const refH = 56;
  const refW = Math.min(refShapes.length * 80, W - MARGIN * 2);
  const refX = (W - refW) / 2;
  const refCellW = refW / refShapes.length;

  svg += `<rect x="${refX}" y="${refY}" width="${refW}" height="${refH}" rx="8" fill="#F8FAFC" stroke="#E2E8F0" stroke-width="1.5" />`;
  svg += `<text x="${W / 2}" y="${refY - 6}" text-anchor="middle" font-family="Inter, sans-serif" font-size="10" fill="#64748B">Reference Shapes:</text>`;

  refShapes.forEach((shape, i) => {
    const cx = refX + i * refCellW + refCellW / 2;
    const cy = refY + refH / 2;
    svg += getShapeSVG(shape, cx, cy, 42, getFill(shape), getStroke(shape), getStrokeW());
    svg += `<text x="${cx}" y="${cy + 28}" text-anchor="middle" font-family="Inter, sans-serif" font-size="8" fill="#94A3B8">${shape}</text>`;
  });

  // Puzzles grid
  const puzzleTop = refY + refH + 24;
  const availH = H - puzzleTop - MARGIN - 35;
  const cols = puzzles.length <= 3 ? puzzles.length : Math.min(3, puzzles.length);
  const rows = Math.ceil(puzzles.length / cols);
  const puzzleAreaW = W - MARGIN * 2;
  const puzzleCellW = puzzleAreaW / cols;
  const puzzleCellH = availH / rows;
  const subGridMaxSize = Math.min(puzzleCellW - 30, puzzleCellH - 30, 130);

  puzzles.forEach((puzzle, idx) => {
    const col = idx % cols;
    const row = Math.floor(idx / cols);
    const pSize = puzzle.grid.length;
    const cellSz = subGridMaxSize / pSize;
    const px = MARGIN + col * puzzleCellW + (puzzleCellW - subGridMaxSize) / 2;
    const py = puzzleTop + row * puzzleCellH + (puzzleCellH - subGridMaxSize) / 2;

    // Puzzle number
    svg += `<text x="${px + subGridMaxSize / 2}" y="${py - 6}" text-anchor="middle" font-family="Nunito, sans-serif" font-size="11" font-weight="700" fill="#64748B">${idx + 1}.</text>`;

    // Grid border
    svg += `<rect x="${px}" y="${py}" width="${subGridMaxSize}" height="${subGridMaxSize}" fill="none" stroke="#CBD5E1" stroke-width="1.5" rx="3" />`;

    // Grid lines
    if (config.showGridLines) {
      for (let i = 1; i < pSize; i++) {
        svg += `<line x1="${px + i * cellSz}" y1="${py}" x2="${px + i * cellSz}" y2="${py + subGridMaxSize}" stroke="#E2E8F0" stroke-width="0.8" />`;
        svg += `<line x1="${px}" y1="${py + i * cellSz}" x2="${px + subGridMaxSize}" y2="${py + i * cellSz}" stroke="#E2E8F0" stroke-width="0.8" />`;
      }
    }

    // Cells
    puzzle.grid.forEach((gridRow, r) => {
      gridRow.forEach((cell, c) => {
        const cx = px + c * cellSz + cellSz / 2;
        const cy = py + r * cellSz + cellSz / 2;
        if (cell.isBlank) {
          svg += `<text x="${cx}" y="${cy + 5}" text-anchor="middle" font-family="Inter, sans-serif" font-size="${cellSz * 0.4}" fill="#CBD5E1">?</text>`;
          svg += `<rect x="${cx - cellSz * 0.38}" y="${cy - cellSz * 0.38}" width="${cellSz * 0.76}" height="${cellSz * 0.76}" rx="4" fill="none" stroke="#CBD5E1" stroke-width="1" stroke-dasharray="4,3" />`;
        } else {
          svg += getShapeSVG(cell.shape, cx, cy, cellSz * shapeScale, getFill(cell.shape), getStroke(cell.shape), getStrokeW(), cell.rotation);
        }
      });
    });
  });

  // Answer key
  if (config.showAnswerKey) {
    const answers = puzzles.map((p, i) => `${i + 1}:${p.answer}`).join('  ');
    svg += `<text x="${W / 2}" y="${H - MARGIN - 28}" text-anchor="middle" font-family="Inter, sans-serif" font-size="9" fill="#94A3B8">Answers: ${answers}</text>`;
  }

  return svg;
}

// ========== MODE 3: MATCH PATTERN ==========
function renderPatternMode(
  config: WorksheetConfig,
  data: WorksheetData,
  shapeScale: number,
  getFill: (s: ShapeName) => string,
  getStroke: (s: ShapeName) => string,
  getStrokeW: () => number,
) {
  const puzzles = data.patternPuzzles!;
  let svg = '';

  const startY = MARGIN + 88;
  const availH = H - startY - MARGIN - 35;
  const rowH = availH / puzzles.length;
  const patternBoxSize = Math.min(rowH - 16, 90);
  const optionBoxSize = Math.min(patternBoxSize * 0.82, 68);

  const leftColX = MARGIN + 20;
  const rightColX = W / 2 + 10;
  const optionSpacing = (W - rightColX - MARGIN - 10) < optionBoxSize * 3.5
    ? optionBoxSize + 8
    : optionBoxSize + 16;

  puzzles.forEach((puzzle, pIdx) => {
    const rowY = startY + pIdx * rowH + (rowH - patternBoxSize) / 2;

    // Row number
    svg += `<text x="${leftColX - 12}" y="${rowY + patternBoxSize / 2 + 4}" text-anchor="middle" font-family="Nunito, sans-serif" font-size="13" font-weight="700" fill="#64748B">${pIdx + 1}.</text>`;

    // Draw pattern (left side)
    svg += renderMiniGrid(puzzle.pattern, leftColX, rowY, patternBoxSize, shapeScale, getFill, getStroke, getStrokeW, config.showGridLines);

    // Arrow
    const arrowX = leftColX + patternBoxSize + 14;
    const arrowY = rowY + patternBoxSize / 2;
    svg += `<line x1="${arrowX}" y1="${arrowY}" x2="${arrowX + 20}" y2="${arrowY}" stroke="#94A3B8" stroke-width="1.5" />`;
    svg += `<polygon points="${arrowX + 20},${arrowY - 4} ${arrowX + 28},${arrowY} ${arrowX + 20},${arrowY + 4}" fill="#94A3B8" />`;

    // Draw 3 options (right side)
    puzzle.options.forEach((option, oIdx) => {
      const ox = rightColX + oIdx * optionSpacing;
      const oy = rowY + (patternBoxSize - optionBoxSize) / 2;

      // Option label
      svg += `<text x="${ox + optionBoxSize / 2}" y="${oy - 4}" text-anchor="middle" font-family="Inter, sans-serif" font-size="9" font-weight="600" fill="#94A3B8">${String.fromCharCode(65 + oIdx)}</text>`;

      svg += renderMiniGrid(option, ox, oy, optionBoxSize, shapeScale * 0.85, getFill, getStroke, getStrokeW, false);

      // Connection dot for drawing lines
      svg += `<circle cx="${ox + optionBoxSize / 2}" cy="${oy + optionBoxSize + 8}" r="3" fill="none" stroke="#CBD5E1" stroke-width="1" />`;
    });

    // Connection dot on pattern side
    svg += `<circle cx="${leftColX + patternBoxSize / 2}" cy="${rowY + patternBoxSize + 8}" r="3" fill="none" stroke="#CBD5E1" stroke-width="1" />`;
  });

  // Answer key
  if (config.showAnswerKey) {
    const answers = puzzles.map((p, i) => `${i + 1}→${String.fromCharCode(65 + p.correctIndex)}`).join('  ');
    svg += `<text x="${W / 2}" y="${H - MARGIN - 28}" text-anchor="middle" font-family="Inter, sans-serif" font-size="9" fill="#94A3B8">Answers: ${answers}</text>`;
  }

  return svg;
}

function renderMiniGrid(
  grid: { shape: ShapeName; rotation?: number }[][],
  x: number,
  y: number,
  size: number,
  scale: number,
  getFill: (s: ShapeName) => string,
  getStroke: (s: ShapeName) => string,
  getStrokeW: () => number,
  showLines: boolean,
): string {
  const rows = grid.length;
  const cols = grid[0].length;
  const cellW = size / cols;
  const cellH = size / rows;
  let svg = '';

  svg += `<rect x="${x}" y="${y}" width="${size}" height="${size}" fill="none" stroke="#CBD5E1" stroke-width="1.5" rx="3" />`;

  if (showLines) {
    for (let i = 1; i < cols; i++) {
      svg += `<line x1="${x + i * cellW}" y1="${y}" x2="${x + i * cellW}" y2="${y + size}" stroke="#E2E8F0" stroke-width="0.8" />`;
    }
    for (let i = 1; i < rows; i++) {
      svg += `<line x1="${x}" y1="${y + i * cellH}" x2="${x + size}" y2="${y + i * cellH}" stroke="#E2E8F0" stroke-width="0.8" />`;
    }
  }

  grid.forEach((row, r) => {
    row.forEach((cell, c) => {
      const cx = x + c * cellW + cellW / 2;
      const cy = y + r * cellH + cellH / 2;
      svg += getShapeSVG(cell.shape, cx, cy, Math.min(cellW, cellH) * scale, getFill(cell.shape), getStroke(cell.shape), getStrokeW(), cell.rotation);
    });
  });

  return svg;
}

// ========== MODE 4: FIND AND COUNT ==========
function renderCountMode(
  config: WorksheetConfig,
  data: WorksheetData,
  shapeScale: number,
  getFill: (s: ShapeName) => string,
  getStroke: (s: ShapeName) => string,
  getStrokeW: () => number,
) {
  const puzzle = data.countPuzzle!;
  const { grid, targetShapes } = puzzle;
  const ROWS = grid.length;
  const COLS = grid[0].length;

  let svg = '';

  // Target shapes reference boxes at top
  const refY = MARGIN + 85;
  const refH = 62;
  const boxCount = targetShapes.length;
  const totalRefW = Math.min(boxCount * 100, W - MARGIN * 2);
  const refX = (W - totalRefW) / 2;
  const boxW = totalRefW / boxCount;

  targetShapes.forEach((shape, i) => {
    const bx = refX + i * boxW + 4;
    const bw = boxW - 8;
    svg += `<rect x="${bx}" y="${refY}" width="${bw}" height="${refH}" rx="6" fill="#F8FAFC" stroke="#CBD5E1" stroke-width="1.5" />`;
    svg += getShapeSVG(shape, bx + bw / 2, refY + 26, 36 * shapeScale, getFill(shape), getStroke(shape), getStrokeW());
    // Blank line for writing count
    svg += `<line x1="${bx + bw * 0.25}" y1="${refY + refH - 10}" x2="${bx + bw * 0.75}" y2="${refY + refH - 10}" stroke="#94A3B8" stroke-width="1.5" />`;
  });

  // Main 6x8 grid
  const gridTop = refY + refH + 18;
  const gridAreaH = H - gridTop - MARGIN - 35;
  const gridAreaW = W - MARGIN * 2;
  const cellW = gridAreaW / COLS;
  const cellH = gridAreaH / ROWS;
  const cellSize = Math.min(cellW, cellH);
  const gridW = cellSize * COLS;
  const gridH = cellSize * ROWS;
  const gridX = (W - gridW) / 2;

  svg += `<rect x="${gridX}" y="${gridTop}" width="${gridW}" height="${gridH}" fill="none" stroke="#CBD5E1" stroke-width="2" rx="4" />`;

  if (config.showGridLines) {
    for (let c = 1; c < COLS; c++) {
      svg += `<line x1="${gridX + c * cellSize}" y1="${gridTop}" x2="${gridX + c * cellSize}" y2="${gridTop + gridH}" stroke="#E2E8F0" stroke-width="0.8" />`;
    }
    for (let r = 1; r < ROWS; r++) {
      svg += `<line x1="${gridX}" y1="${gridTop + r * cellSize}" x2="${gridX + gridW}" y2="${gridTop + r * cellSize}" stroke="#E2E8F0" stroke-width="0.8" />`;
    }
  }

  grid.forEach((row, r) => {
    row.forEach((cell, c) => {
      const cx = gridX + c * cellSize + cellSize / 2;
      const cy = gridTop + r * cellSize + cellSize / 2;
      svg += getShapeSVG(cell.shape, cx, cy, cellSize * shapeScale, getFill(cell.shape), getStroke(cell.shape), getStrokeW(), cell.rotation);
    });
  });

  // Answer key
  if (config.showAnswerKey) {
    const answers = targetShapes.map(s => `${s}: ${puzzle.counts[s]}`).join('   ');
    svg += `<text x="${W / 2}" y="${gridTop + gridH + 16}" text-anchor="middle" font-family="Inter, sans-serif" font-size="9" fill="#94A3B8">Answers: ${answers}</text>`;
  }

  return svg;
}
